[#setup]

== Setting up your local development environment

This section will guide you through setting up your local development environment for StarkNet development, covering the following topics:

* Installing prerequisites
* Installing the `starknet` CLI
* Installing the Cairo compiler

=== Prerequisites

Before you proceed, ensure that you have the following prerequisites installed on your system:

* https://www.python.org/downloads/release/python-390/[Python 3.9]
* https://www.rust-lang.org/tools/install[Rust]

=== StarkNet CLI Installation

To install the StarkNet CLI, follow these steps:

* *Set up your virtual environment*:

We recommend working inside a Python virtual environment. This isolates your project's dependencies from your system's global Python installation. To create and activate a virtual environment, you can use either `venv` or `pyenv`.

  a. Using `venv`:

  [source, bash]
  ----
  # Create a virtual environment named "cairo_venv"
  python3.9 -m venv ~/cairo_venv
  # Activate the virtual environment
  source ~/cairo_venv/bin/activate
  ----

  b. Using `pyenv`:

  [source, bash]
  ----
  # Install pyenv
  curl https://pyenv.run | bash

  # Add the following lines to your .bashrc or .zshrc
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"

  # Restart your terminal and run the following commands
  pyenv install 3.9.0
  pyenv virtualenv 3.9.0 cairo_venv
  pyenv activate cairo_venv
  ----

After creating and activating the virtual environment, you should see `(cairo_venv)` in the command line prompt, indicating that the virtual environment is active, for example:

[source, bash]
----
(cairo_venv) satoshi@nakamoto-notebook %
----

* *Install the necessary dependencies for your operating system*:

Before installing the StarkNet CLI, you need to install some system-specific dependencies. Follow the instructions for your operating system:

  a. Ubuntu:

  [source, bash]
  ----
  sudo apt install -y libgmp3-dev
  ----

  b. Mac:

  [source, bash]
  ----
  brew install gmp
  ----

Once you have installed the system-specific dependencies, proceed with installing the Python packages required for StarkNet CLI:

  [source, bash]
  ----
  pip install ecdsa fastecdsa sympy
  ----

These Python packages provide cryptographic and mathematical functionality needed by the StarkNet CLI.

* *Install the StarkNet CLI*:

Now that you have set up the environment and installed the dependencies, you can install the StarkNet CLI. Follow these steps:

  a. Uninstall any previous version of `cairo-lang`:

  [source, bash]
  ----
  pip uninstall cairo-lang
  ----

  b. Install the latest version of `cairo-lang`:

  [source, bash]
  ----
  pip install cairo-lang
  ----

After you have installed the StarkNet CLI, verify your installation by checking the version:

  [source, bash]
  ----
  starknet --version
  ----

The output should show the installed version of StarkNet CLI. Make sure the version matches https://github.com/starkware-libs/cairo-lang/releases[the latest release].


=== Cairo Compiler Installation

To install the Cairo compiler, follow these steps:

. Clone the Cairo repository and set it up:

[source, bash]
----
# Go to your $HOME directory
cd ~/
# Clone the Cairo compiler repo to a folder called .cairo in your home directory
git clone https://github.com/starkware-libs/cairo/ .cairo

# Checkout the working branch and generate the release binaries
cd .cairo/
git checkout tags/v1.0.0-alpha.6
cargo build --all --release
----

. Add Cairo executables to your PATH:

Update your `.bashrc` or `.zshrc` file to add the Cairo binaries to your `PATH` environment variable:

   [source, bash]
   ----
   # Add the command below to your .bashrc or .zshrc
   export PATH="$HOME/.cairo/target/release:$PATH"
   ----

   Open a new shell and check that the following command returns a version number:

   [source, bash]
   ----
   cairo-compile --version
   ----

Congratulations! Your local development environment for StarkNet is now set up. You can now start building, deploying, and interacting with Cairo smart contracts.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____