[id="recursion"]

= Recursion instead of loops and an example of implications

As stated in the Cairo documentation https://www.cairo-lang.org/docs/hello_cairo/intro.html?highlight=loops#recursion-instead-of-loops[here], we should avoid loops when using Cairo.
The main underlying reason is:

"You may have noticed that we've used recursion in the code above rather than the loop structure you may have expected.
The main reason for this is that the Cairo memory is immutable -- once you write the value of a memory cell, this cell cannot change in the future."

Having said that, a developer not coming with a Solidity background might be puzzled by some implications of this property.
This is the case when using https://www.cairo-lang.org/docs/hello_starknet/more_features.html?highlight=mapping[storage mappings].
One good example is https://github.com/starknet-edu/starknet-cairo-101/blob/47c8bd04e762f3c469d6d8d24b169b5145ba9acc/contracts/ex13.cairo#L144[this one] where a storage mapping is filled with some input array provided by the user at contract creation time.
In order to validate ex13 of https://github.com/starknet-edu/starknet-cairo-101[starknet-cairo-101], you will have to find the transaction corresponding to the creation of the contract and reverse-engineer the values in the `values_mapped_secret_storage` storage mapping based on what has been passed to the contract constructor.
In order to do so, you will have to have a deep understanding of the type of recursion used.

Please, navigate to link:./recursion/cairo/recursion.cairo[recursion/cairo/recursion.cairo] and read the code as well with comments to have two examples of recursions.
One of which is applicable to how storage mappings deal with it.
Instructions on how to compile and run the program are embedded in https://github.com/starknet-edu/starknetbook/blob/main/chapters/modules/chapter_1/pages/contracts/cairo/recursion.cairo[recursion/cairo/recursion.cairo].

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
