[id="starknet_contracts"]

= Starknet Contracts

"Starknet is a permissionless decentralized ZK-Rollup operating as an L2 network over Ethereum, where any dApp can achieve unlimited scale for its computation without compromising Ethereum's composability and security."
-- https://docs.starknet.io/documentation/[Starknet Documentation].

Contracts on Starknet are written in Cairo. You can transpile a Solidity contract to Cairo via https://github.com/NethermindEth/warp[Warp] or use EVM bytecode using the Kakarot ZKEVM. However, the real power of Starknet will be harnessed by contracts written in Cairo itself.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
