[id="transpiling"]

= Transpiling Solitidy code into Cairo

Try transpiling your Solidity code into Cairo!
Run the following code snippet in your terminal to link:starknetbook/camp_3/contracts/solidity/ERC20.sol[Warp an ERC20].

[,bash]
----
cd contracts/solidity
warp transpile ERC20.sol WARP
warp deploy ERC20.json
----

Congratulations on finishing Camp 1!
You are closer to the moon.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
