[id="whyCairo"]

= Why Cairo?

StarkNet's scalability tool, ZK Roll-ups, enable a new paradigm called Provable Computation. In this paradigm, we allow programs to prove they have been executed without having to be re-run. In order to write such provable programs, we need a programming language that can be effective and be easily learnt by developers. 

If you are looking for a cost-effective provable computation programming language, consider Cairo. It is native to Provable Computation and includes low-level access to memory, underlying primitives, and functional-style programming. Listed below, are some of the benefits of Cairo: +

* It is a specially designed, provable language for smart contracts +
* It is not bounded by the EVM +
* Its functions are imported rather than inherited +
* It supports Solidity to Cairo transpiler +
* It includes full low-level access to underlying primitives +

The upgraded version of Cairo offers Rust like syntax, which is easier to understand for developers.

== Contributing

🎯 +++<strong>+++STARKer: +++</strong>+++ This book is an open source effort, made possible only by contributions from readers like you. If you are interested in making this resource better for other users - please suggest a change by following the instructions https://github.com/starknet-edu/starknetbook/blob/antora-front/CONTRIBUTING.adoc[here].
🎯