= Why Starknet?

== The Problem

Ethereum scaling has been a major discussion topic since the network was launched. Commonly known as the blockchain trilemma, most applications have to choose 2/3 features between scalability, security and decentralization and compromise on any one of them.

Several NFT launches have seen gas fee spike up to 1000s of dollars congesting the network, thereby casting doubts on Ethereum's ability to scale.

== The Solution

Layer 2 solutions can offer scalability to Ethereum by helping offload a lot of computational work done at the Ethereum layer to another layer. Roll up solutions have the potential to scale Ethereum in a way that billions of users across the globe can use it seamlessly.

Amongst the existing rollup solutions, it is well known that zk-Rollups are going to be the future roadmap of Ethereum. Ethereum is the only truly decentralised blockchain, and with that comes the sort of open source innovation and soul that is so unique to the Ethereum community. We bet on decentralisation, innovation, and general purpose logic and composability.

Starknet, built on the concept of Validity Proofs(ZK Proofs under the hood) attempts to tackle the Blockchain Trilemma and provide a system that is inclusively accountable, decentralized, scalable, and secure through the use of zero-knowledge STARK proofs.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____