[id="devnet"]

= Devnet

由于测试网上的交易需要时间才能完成，因此最好在本地进行开发和测试。我们将使用 https://github.com/0xSpaceShard/starknet-devnet[hard Labs 开发的 devnet]。 我们可以认为这一步骤相当于 Ganache。也就是说，它模拟了 Starknet 的测试网（alpha goerli）。

安装使用：

[,Bash]
----
pip install starknet-devnet
----

重新启动终端并运行 starknet-devnet --version 以检查安装是否成功。检查您是否安装 https://github.com/0xSpaceShard/starknet-devnet/releases[最新版本]。如果没有，请运行 pip install --upgrade starknet-devnet。 https://shard-labs.github.io/starknet-devnet/docs/intro[这是文档]。

在单独的 shell（或选项卡）中初始化 devnet

[,Bash]
----
starknet-devnet \
    --accounts 3 \
    --gas-price 250 \
    --seed 0 \
    --port 5000
----

我们将得到:

[,Bash]
----
Account #0
Address: 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a
Public key: 0x7e52885445756b313ea16849145363ccb73fb4ab0440dbac333cf9d13de82b9
Private key: 0xe3e70682c2094cac629f6fbed82c07cd

Account #1
Address: 0x69b49c2cc8b16e80e86bfc5b0614a59aa8c9b601569c7b80dde04d3f3151b79
Public key: 0x175666e92f540a19eb24fa299ce04c23f3b75cb2d2332e3ff2021bf6d615fa5
Private key: 0xf728b4fa42485e3a0a5d2f346baa9455

Account #2
Address: 0x7447084f620ba316a42c72ca5b8eefb3fe9a05ca5fe6430c65a69ecc4349b3b
Public key: 0x58100ffde2b924de16520921f6bfe13a8bdde9d296a338b9469dd7370ade6cb
Private key: 0xeb1167b367a9c3787c65c1e582e2e662

Initial balance of each account: 1000000000000000000000 WEI
Seed to replicate this account sequence: 0
WARNING: Use these accounts and their keys ONLY for local testing. DO NOT use them on the mainnet or live networks because you will LOSE FUNDS.

 * Listening on http://127.0.0.1:5000/ (Press CTRL+C to quit)
----

我们可以运行  `curl http://127.0.0.1:5000/is_alive`  来检查 devnet 是否处于激活状态。如果它处于激活状态，将会显示 `Alive!!!%` 。

我们创建了三个账户，每笔交易的成本为250wei的Gas。每次激活我们的开发网络并添加该种子号时，种子号将帮助我们获得相同的帐户。也就是说，我们可以选择任意一个种子号，但是如果我们要得到相同的账号，就应该选择相同的种子。我们表示我们想要使用端口 5000，但是，请随意添加任何方便的端口。我们的账户基于  https://github.com/OpenZeppelin/cairo-contracts[Open Zepellin 为Cairo] 开发的代码和标准。

请跟踪我们的 devnet 运行的地址。上面的例子是 `http://127.0.0.1:5000`。我们稍后会用到它。

与devnet的交互和与测试网的交互非常相似。如果您想查看 starknet-devnet 调用中可用的所有参数，您可以调用 starknet-devnet --help 或转到 https://shard-labs.github.io/starknet-devnet/docs/intro[文档]。



== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的[指南](https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc) 并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区

