[id="environment"]

在前面的章节中，您已经在本地设备上安装了 Python、Rust、Cairo 和 Starknet CLI。 这些安装为在 Starknet 生态系统中工作提供了基础。 为了增强您的开发体验，我们建议安装一些额外的工具。

== Cairo语言服务器

开发人员经常使用流行的 IDE，例如 VS Code 或 Emacs。 尽管这些 IDE 非常适合编写代码，但它们本身并不支持 Starknet 生态系统。 Cairo Language Server 通过为 IDE 提供必要的信息来弥补这一差距，以获得更好的开发体验，包括自动完成、语法突出显示和错误检查。

要安装开罗语言服务器，请按照此处的说明进行操作。 如果您在 VS Code 中安装了以前的 Cairo 0.x 扩展，请确保禁用它。 运行以下命令：

[source, bash]
----
which cairo-language-server | pbcopy
----

然后，将该值粘贴到编辑器设置中 Cairo 1.0 扩展的 `languageServerPath` 字段中。

== Scarb

Scarb 是为 Cairo 和 Starknet 生态系统设计的构建工具链和包管理器。 它以 Cargo 为模型，旨在为 Rust 开发人员提供熟悉的体验。 要安装 Scarb，请按照此处的本地构建说明进行操作。 通过运行以下命令测试安装：

[source, bash]
----
scarb --version
----

有关使用 Scarb 的更多详细信息，请参阅本书的第 2 章。有了这些工具，你就可以在 Starknet 生态系统中很好地开发和遨游。

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
