[id="chapter_3"]

= Starknet 工具

如果您准备好开始构建可扩展的 web3 应用程序——是时候选择您的技术栈了。 由于我们出色的社区，Starknet 作为第一个基于 ZK rollup成立以来取得了显着发展。 今天，您将找到在 Starknet 上构建去中心化应用程序 (dApp) 所需的所有必要工具。

始终欢迎贡献者加入 Starknet 社区，帮助改进现有工具或创建新的解决方案。

在本章中，您可以了解以下主题：

- 环境：有用的配置可加快您的开发过程
- 钱包：使用 Argent 和 Braavos 等 Starknet 钱包接口
- 互动游戏教程：以有趣的方式学习智能合约
- 架构：为你作为开发者的经验提供结构
- 通用 SDK：针对不同的编程语言可使用 Starknet.js、Starknet-rs、Starknet_py 和 Caigo
- 工具和应用：开发时可能会用到的其他东西

到本章结束时，您将全面了解 Starknet 生态系统中可用的工具以及它们能如何帮助您有效地构建和部署 dApp。

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
