[id="protostar"]

= Protostar

https://docs.swmansion.com/protostar/[Protostar] is a highly practical development platform for the StarkNet universe. This tool eases the process of managing dependencies, compiling projects, running tests, and interacting with the StarkNet chain. Protostar allows developers to write, test and deploy their Cairo contracts in a streamlined manner.

== Installation

To begin, you'll need to install Protostar on your local machine. This process currently supports Linux and MacOS systems (Windows support is in progress).

Install Protostar by opening a terminal and running the following command:

[source,bash]
----
curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
----

After the installation process, restart the terminal. Check that the version of your installed Protostar matches `0.11.0` for compatibility with Cairo 1.0. If it does not, update your Protostar version using the command:

[source,bash]
----
protostar upgrade
----

== Supported Software Versions

Ensure you're keeping your Protostar upgraded to the latest version.

Protostar doesn't currently support Windows. 

== Verifying Installation

Once Protostar is installed, verify it by checking the version with the command:

[source,bash]
----
protostar -v
----

The output should be as follows:

[source,bash]
----
Protostar version: 0.12.0                                                                                                       
Cairo-lang version: 0.11.1.1
Cairo 1 compiler version: 1.0.0rc0
21:03:44 [INFO] Execution time: 1.34 s
----

== Initiating a New Cairo Project

After successful installation and verification of Protostar, initiate a new project by running:

[source,bash]
----
protostar init my_project
cd my_project
----

The structure of your project directory should be similar to:

[source,bash]
----
my_project/
├── hello_starknet/
│   ├── src/
│   │   ├── business_logic/
│   │   │   └── utils.cairo
│   │   ├── contracts/
│   │   │   └── hello_starknet.cairo
│   │   ├── business_logic.cairo
│   │   ├── contracts.cairo
│   │   └── lib.cairo
│   └── cairo_project.toml
├── tests/
│   ├── test_hello_starknet.cairo
│   └── test_utils.cairo
└── protostar.toml
----

The most important thing to notice is how we have structured both these contracts as standalone crates. Each smart contract in Protostar must be built as its own crate and each contract is its own module decorated with the `[contract]` decorator.

Explore the official Protostar documentation for more details on structuring your project: https://docs.swmansion.com/protostar/docs/cairo-1/introduction


== Testing Contracts

In the realm of Cairo smart contracts, there are two predominant ways to test your contracts: within Cairo itself, or with Python, Javascript, or Rust. 

The Cairo approach is often preferred, as it prevents developers from having to deploy contracts each time they need to be tested and eliminates the necessity of learning a new language for testing purposes.

Execute tests using the command:

[source,bash]
----
protostar test
----

A successful test execution will provide an output resembling:

[source,bash]
----
Collected 2 suites, and 3 test cases (11.32)                                                                                                                    
[PASS] tests/test_utils.cairo test_returns_two (time=0.00s)                                                                                                     
[PASS] tests/test_hello_starknet.cairo test_increase_balance (time=25.81s)                                                                                      
[PASS] tests/test_hello_starknet.cairo test_cannot_increase_balance_with_zero_value (time=25.19s)                                                               
Test suites: 2 passed, 2 total                                                                                                                                  
Tests:       3 passed, 3 total
Seed:        720541691
21:17:52 [INFO] Execution time: 66.70 s
----

== Compile the Project

== Project Compilation

Before a project can be deployed on the network, it must be compiled into a form that the StarkNet network can understand and execute. Protostar makes this process easy with its `build` command. 

To compile your Cairo1 project, use the build command:

[source,bash]
----
protostar build
----

If your compilation was successful, the output will be similar to this:

[source,bash]
----
21:00:22 [INFO] Building cairo1 contracts                                                                                                                       
21:00:27 [INFO] Contracts built successfully
21:00:27 [INFO] Execution time: 6.22 s
----

== Contract Declaration

After successfully compiling your project, the next step is to declare your contracts. This process informs the network of your intention to deploy a new contract (review Chapter 2 for more details on the contract declaration process).

Before declaring contracts, it's essential to first set the environment variable for your private key:

[source,bash]
----
export PROTOSTAR_ACCOUNT_PRIVATE_KEY=0x...
----

You can then declare your contracts with the following command:

[source,bash]
----
protostar declare hello_starknet \
  --network testnet \
  --account-address YOUR_ACCOUNT_ADDRESS \
  --max-fee auto
----

Note: Replace `YOUR_ACCOUNT_ADDRESS` with your actual account address.

Successful declaration will generate a class hash and output similar to:

[source,bash]
----
Declare transaction was sent.                                                                                                                                   
Class hash: 0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd
StarkScan https://testnet.starkscan.co/class/0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd
Voyager   https://goerli.voyager.online/class/0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd
Transaction hash: 0x03d048f8dc599c7d9bad1e5a7a039c35463b9479f0966766bc0df03cd89d6d7d
StarkScan https://testnet.starkscan.co/tx/0x03d048f8dc599c7d9bad1e5a7a039c35463b9479f0966766bc0df03cd89d6d7d
Voyager   https://goerli.voyager.online/tx/0x03d048f8dc599c7d9bad1e5a7a039c35463b9479f0966766bc0df03cd89d6d7d
21:01:23 [INFO] Execution time: 27.95 s
----

== Contract Deployment

After declaring your contract, the next step is to deploy it on the network. Deployment makes your contract live and interactable on the StarkNet.

To deploy your contract, use the class hash generated from the declaration step and the `protostar deploy` command:

[source,bash]
----
protostar deploy \
  0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd \
  --network testnet \
  --account-address YOUR_ACCOUNT_ADDRESS \
  --max-fee auto
----

Note: Replace `YOUR_ACCOUNT_ADDRESS` with your actual account address. 

The '0x' address following the deploy command is the Class Hash that was generated during contract declaration.

Successful deployment will provide a contract address and output similar to this:

[source,bash]
----
Invoke transaction was sent to the Universal Deployer Contract.                                                                                                 
Contract address: 0x02341c459847cf220671ab873e14d853197c74e239c3b5815b0aa2e85bc37ebd
StarkScan https://testnet.starkscan.co/contract/0x02341c459847cf220671ab873e14d853197c74e239c3b5815b0aa2e85bc37ebd
Voyager   https://goerli.voyager.online/contract/0x02341c459847cf220671ab873e14d853197c74e239c3b5815b0aa2e85bc37ebd
Transaction hash: 0x03406b79b189d8752cff632ea8e0df332d7be7e27ffbc453fbf210c7384c0676
StarkScan https://testnet.starkscan.co/tx/0x03406b79b189d8752cff632ea8e0df332d7be7e27ffbc453fbf210c7384c0676
Voyager   https://goerli.voyager.online/tx/0x03406b79b189d8752cff632ea8e0df332d7be7e27ffbc453fbf210c7384c0676
21:25:26 [INFO] Execution time: 3.22 s
----

== A Simple Demo 

To learn how you can get started with Protostar, let's create a simple project. First, navigate to your terminal and execute:

[source,bash]
----
git clone https://github.com/SupremeSingh/protostar-cairo1-template.git
cd protostar-cairo1-template
----

Now, you have access to a basic Protostar project that implements two smart contracts along with additional business logic in `Cairo 1.0`. Before proceeding, it's advisable to familiarize yourself with the code in both `erc20.cairo` and `hello_starknet.cairo`. 

For a deeper understanding of testing, it is highly recommended to examine the tests in `tests/test_erc20.cairo` and compare them with the original contract in `contracts/erc20.cairo`.

== Debugging

For code debugging, it's beneficial to be able to print out values or isolate errors in match statements. Protostar already provides these functionalities. 

To print out values, use the following:

[source,bash]
----
use array::ArrayTrait;
use array::ArrayTCloneImpl;
use array::SpanTrait;
use debug::PrintTrait;
use clone::Clone;

array.span().snapshot.clone().print(); // Print an array value
felt.print() // Print an individual value
----

You can also use match statements like so: 

[source,bash]
----
match invoke(deployed_contract_address, 'panic_with', @panic_data) {
    Result::Ok(x) => assert(false, 'Shouldnt have succeeded'),
    Result::Err(x) => {
        assert(x.first() == 'error', 'first datum doesnt match');
        assert(*x.panic_data.at(1_u32) == 'data', 'second datum doesntmatch');
    }
}
----

Finally, to make your code interact with StarkNet, you can utilize the comprehensive list of commands provided by Protostar. You can find these commands [here](https://docs.swmansion.com/protostar/docs/cairo-1/interacting-with-starknet).

== Common Gotchas 

- Each test should be named `test_<further name>.cairo` so that the framework can recognize it.
- Tests need to be decorated with `#[test]`, be without parameters, and include an assertion.
- `contract_address_const::<0>()` is the default caller for all invocations.
- A `Prank` needs to be used to change the caller address.
- `u256` values need to be split into two `felt252` values when making a call.
- Protostar currently does not support `#[external]` functions that emit an event for testing. Please wait for the next release.

== Conclusion

Protostar represents a powerful toolset for developing, testing, and deploying smart contracts on the StarkNet network. This guide has introduced you to its main features and demonstrated how to use it in the context of a simple project. Although there are some nuances and "gotchas" to be aware of, the benefits of using Protostar are evident. As the StarkNet ecosystem evolves, tools like Protostar will continue to play a critical role in helping developers build robust, reliable, and secure decentralized applications. Happy coding!


[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
