[id="protostar"]

= Protostar

https://docs.swmansion.com/protostar/[Protostar] 是一个非常实用的 Starknet 开发平台。 该工具简化了管理依赖、编译项目、运行测试以及与 Starknet 链交互的过程。 Protostar 允许开发人员以简化的方式编写、测试和部署他们的 Cairo 合约。

== 安装

首先，您需要在本地计算机上安装 Protostar。该进程目前支持 Linux 和 MacOS 系统（Windows 支持正在进行中）。

通过打开终端并运行以下命令来安装：

[source,bash]
----
curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
----

安装完成后，重新启动终端。 检查您安装的 Protostar 的版本是否为 https://github.com/software-mansion/protostar/releases[most recent version]。如果不是，请使用以下命令更新您的 Protostar 版本：

[source,bash]
----
# Check your current version
protostar -v

# Update to the latest version
protostar upgrade
----

== 支持的软件版本

确保您将 Protostar 升级到最新版本。 Protostar 目前不支持 Windows。

== 验证安装

安装 Protostar 后，通过使用以下命令检查版本来验证它：

[source,bash]
----
protostar -v
----

输出应如下所示：

[source,bash]
----
Protostar version: 0.12.0                                                                                                       
Cairo-lang version: 0.11.1.1
Cairo 1 compiler version: 1.0.0rc0
21:03:44 [INFO] Execution time: 1.34 s
----

注意 Cairo-lang 是 Starknet 网络的版本，Cairo 1 compiler 是 Cairo 编译器的版本。

== 启动新Cairo项目

成功安装和验证 Protostar 后，运行以下命令启动一个新项目：

[source,bash]
----
protostar init my_project
cd my_project
----

您的项目目录的结构应类似于：

[source,bash]
----
my_project/
├── hello_starknet/
│   ├── src/
│   │   ├── business_logic/
│   │   │   └── utils.cairo
│   │   ├── contracts/
│   │   │   └── hello_starknet.cairo
│   │   ├── business_logic.cairo
│   │   ├── contracts.cairo
│   │   └── lib.cairo
│   └── cairo_project.toml
├── tests/
│   ├── test_hello_starknet.cairo
│   └── test_utils.cairo
└── protostar.toml
----

需要注意的重点是我们如何将这两个合约构建为独立的库。 Protostar 中的每个智能合约都必须构建为自己的库，每个合约都是用  `[contract]`  装饰器装饰的自己的模块。

浏览官方 Protostar 文档，了解有关构建项目的更多详细信息： https://docs.swmansion.com/protostar/docs/cairo-1/introduction


== 测试合约

在 Cairo 智能合约领域，有两种主要的方法来测试你的合约：在 Cairo 内部，或者使用 Python、Javascript 或 Rust。

Cairo 内部测试通常是首选，因为它可以避免开发人员每次需要测试时都必须进行合约部署，并且消除了为测试而学习新语言的必要性。

使用命令执行测试：

[source,bash]
----
protostar test
----

成功的测试执行将提供类似于以下内容的输出：

[source,bash]
----
Collected 2 suites, and 3 test cases (11.32)                                                                                                                    
[PASS] tests/test_utils.cairo test_returns_two (time=0.00s)                                                                                                     
[PASS] tests/test_hello_starknet.cairo test_increase_balance (time=25.81s)                                                                                      
[PASS] tests/test_hello_starknet.cairo test_cannot_increase_balance_with_zero_value (time=25.19s)                                                               
Test suites: 2 passed, 2 total                                                                                                                                  
Tests:       3 passed, 3 total
Seed:        720541691
21:17:52 [INFO] Execution time: 66.70 s
----


== 项目编译

在网络上部署项目之前，必须将其编译成 Starknet 网络可以理解和执行的形式。 Protostar 的 build 命令可以使此过程变得简单。

使用build命令编译您的Cairo1项目：

[source,bash]
----
protostar build
----

如果编译成功，输出将类似于：

[source,bash]
----
21:00:22 [INFO] Building cairo1 contracts                                                                                                                       
21:00:27 [INFO] Contracts built successfully
21:00:27 [INFO] Execution time: 6.22 s
----

== 合约声明

成功编译您的项目后，下一步就是声明您的合同。这个过程会通知网络你打算部署一个新合约（查看第 2 章以了解更多关于合约声明过程的细节）。

在声明合约之前，必须先为您的私钥设置环境变量：

[source,bash]
----
export PROTOSTAR_ACCOUNT_PRIVATE_KEY=0x...
----

然后，您可以使用以下命令声明您的合约：

[source,bash]
----
protostar declare hello_starknet \
  --network testnet \
  --account-address YOUR_ACCOUNT_ADDRESS \
  --max-fee auto
----

注意：将  `YOUR_ACCOUNT_ADDRESS`  替换为您的实际帐户地址。

成功的声明将生成类哈希和类似于以下内容的输出：

[source,bash]
----
Declare transaction was sent.                                                                                                                                   
Class hash: 0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd
StarkScan https://testnet.starkscan.co/class/0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd
Voyager   https://goerli.voyager.online/class/0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd
Transaction hash: 0x03d048f8dc599c7d9bad1e5a7a039c35463b9479f0966766bc0df03cd89d6d7d
StarkScan https://testnet.starkscan.co/tx/0x03d048f8dc599c7d9bad1e5a7a039c35463b9479f0966766bc0df03cd89d6d7d
Voyager   https://goerli.voyager.online/tx/0x03d048f8dc599c7d9bad1e5a7a039c35463b9479f0966766bc0df03cd89d6d7d
21:01:23 [INFO] Execution time: 27.95 s
----

== 合约部署

声明合约后，下一步就是将其部署到网络上。合约部署可以让您的合同在 Starknet 上生效并可交互。

要部署您的合约，请使用从声明步骤生成的类哈希和  `protostar deploy`  命令：

[source,bash]
----
protostar deploy \
  0x04ad47b818e8811a8c1df2a03a26381da0232bb7da3cba274831c2cfc9953acd \
  --network testnet \
  --account-address YOUR_ACCOUNT_ADDRESS \
  --max-fee auto
----

注意：将  `YOUR_ACCOUNT_ADDRESS`  替换为您的实际帐户地址。

deploy 命令后的 “0x” 地址是合约声明期间生成的类哈希。

成功部署将提供一个合约地址和类似这样的输出：

[source,bash]
----
Invoke transaction was sent to the Universal Deployer Contract.                                                                                                 
Contract address: 0x02341c459847cf220671ab873e14d853197c74e239c3b5815b0aa2e85bc37ebd
StarkScan https://testnet.starkscan.co/contract/0x02341c459847cf220671ab873e14d853197c74e239c3b5815b0aa2e85bc37ebd
Voyager   https://goerli.voyager.online/contract/0x02341c459847cf220671ab873e14d853197c74e239c3b5815b0aa2e85bc37ebd
Transaction hash: 0x03406b79b189d8752cff632ea8e0df332d7be7e27ffbc453fbf210c7384c0676
StarkScan https://testnet.starkscan.co/tx/0x03406b79b189d8752cff632ea8e0df332d7be7e27ffbc453fbf210c7384c0676
Voyager   https://goerli.voyager.online/tx/0x03406b79b189d8752cff632ea8e0df332d7be7e27ffbc453fbf210c7384c0676
21:25:26 [INFO] Execution time: 3.22 s
----

== 一个简单的演示

要了解如何开始使用 Protostar，让我们创建一个简单的项目。首先，导航到您的终端并执行：

[source,bash]
----
git clone https://github.com/SupremeSingh/protostar-cairo1-template.git
cd protostar-cairo1-template
----

现在，您可以访问一个基本的 Protostar 项目，该项目在  `Cairo 1.0`  中实现了两个智能合约以及其他业务逻辑。 在继续之前，建议您熟悉  `erc20.cairo`  和  `hello_starknet.cairo`  中的代码。

为了更深入地了解测试，强烈建议检查  `tests/test_erc20.cairo`  中的测试，并将它们与  `contracts/erc20.cairo`  中的原始合约进行比较。

== 调试

对于代码调试，能够打印出值或隔离匹配语句中的错误是有益的。Protostar 已经提供了这些功能。

要打印出值，请使用以下命令：

[source,bash]
----
use array::ArrayTrait;
use array::ArrayTCloneImpl;
use array::SpanTrait;
use debug::PrintTrait;
use clone::Clone;

array.span().snapshot.clone().print(); // Print an array value
felt.print() // Print an individual value
----

您还可以像这样使用匹配语句：

[source,bash]
----
match invoke(deployed_contract_address, 'panic_with', @panic_data) {
    Result::Ok(x) => assert(false, 'Shouldnt have succeeded'),
    Result::Err(x) => {
        assert(x.first() == 'error', 'first datum doesnt match');
        assert(*x.panic_data.at(1_u32) == 'data', 'second datum doesntmatch');
    }
}
----

最后，为了让您的代码与 Starknet 交互，您可以使用 Protostar 提供的完整命令列表。您可以在 https://docs.swmansion.com/protostar/docs/cairo-1/interacting-with-starknet 找到这些命令。

== 常见的陷阱

- 每个测试都应命名为  `test_<further name>.cairo`  以便框架可以识别它。
- 测试需要用  `#[test]`  修饰，没有参数，并包含一个断言。
-   `contract_address_const::<0>()`  是所有调用的默认调用者。
- 需要使用prank来更改调用者地址。
- 调用时需要将  `u256`  值拆分为两个  `felt252`  值。
- Protostar 目前不支持发出测试事件的  `#[external]`  函数。请等待下一个版本。

== 结论

Protostar 代表了一个强大的工具集，用于在 Starknet 网络上开发、测试和部署智能合约。 本指南向您介绍了它的主要功能，并演示了如何在一个简单项目的环境中使用它。尽管需要注意一些细微差别和“陷阱”，但使用 Protostar 的好处是显而易见的。随着 Starknet 生态系统的发展，像 Protostar 这样的工具将继续在帮助开发人员构建强壮、可靠和安全的去中心化应用程序方面发挥关键作用。编码愉快！


附注

《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

- 无论你是否有所收获，烦请 https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[填写此问卷]，简单回答三个问题，给予我们反馈。
- 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库发起问题单 (Issues)]。




== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的 https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[指南]并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区
