[id="sdk"]

= 软件开发套件 (SDK)

在区块链世界中，软件开发工具包 (SDK) 是一组软件构建工具，专门用于促进特定区块链平台上应用程序的开发。 SDK 提供了一套全面的工具，使开发人员能够以标准化的方式更高效地创建软件应用程序。

Starknet 目前提供以下 SDK：

.Starknet SDKs
|===
|语言|名称

|Python|https://github.com/software-mansion/starknet.py[starknet_py]
|Rust|https://github.com/xJonathanLEI/starknet-rs[starknet-rs]
|Javascript|https://www.starknetjs.com/[starknet.js]
|Golang|https://github.com/dontpanicdao/caigo[Caigo]

|===

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
