[id="starknet-react"]

= Starknet React

====
贡献：我们希望添加一个具体示例，说明如何使用 Starknet React（可能与 starknet.js 交互）。如果您有使用 Starknet React 的项目，请提交 PR。
====

Starknet React 是由 [Apibara](https://github.com/apibara) 团队开发的, 是 React 提供者的一个开源合集及 Starknet 的钩子。 

要开始使用 Starknet-React，首先安装适当的包管理器 PNPM：

[source, bash]
----
npm install -g pnpm
----

接下来，通过运行修改 React 样板：

[source, bash]
----
pnpm add @starknet-react/core
pnpm add get-starknet starknet
----

最后，将 `App` 对象包装在 `index` 文件中，如下所示：

[source, javascript]
----
import { StarknetConfig } from '@starknet-react/core'

function App() {
  return (
    <StarknetConfig>
      <YourApp />
    </StarknetConfig>
  )
}
----

探索示例项目, 请访问  https://github.com/apibara/starknet-react/tree/main/website


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____

== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的[指南](https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc)并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区
