[id="starknet-react"]

= Starknet React

====
贡献：我们希望添加一个具体示例，说明如何使用 Starknet React（可能与 starknet.js 交互）。 如果您有使用 Starknet React 的项目，请提交 PR。
====

Starknet React是由[Apibara](https://github.com/apibara) 团队开发的, 为Starknet上的提供商和钩子打造的一个开源的集合。 

要开始使用 Starknet-React，首先安装适当的包管理器 PNPM：

[source, bash]
----
npm install -g pnpm
----

接下来，通过运行修改 React 样板：

[source, bash]
----
pnpm add @starknet-react/core
pnpm add get-starknet starknet
----

最后，将 `App` 对象包装在 `index` 文件中，如下所示：

[source, javascript]
----
import { StarknetConfig } from '@starknet-react/core'

function App() {
  return (
    <StarknetConfig>
      <YourApp />
    </StarknetConfig>
  )
}
----

探索示例项目, 请访问(https://github.com/apibara/starknet-react/tree/main/website).


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
