[id="vue-stark-boil"]
s
= Vue Stark Boil

====
贡献：我们正在寻找如何使用 Starknet Vue 的具体示例。 如果您有使用 Starknet React 的项目，请提交 PR。
====

Starknet生态系统提供了适用于 Vue 和 React 的框架。 对于那些喜欢 Vue 的人来说，由 [Don't Panic DAO](https://github.com/dontpanicdao) 团队开发的 vue-stark-boil 是一个不错的选择。

首先，从(https://github.com/dontpanicdao/vue-stark-boil) 将项目克隆到您的设备。 要更深入地了解 Vue，请访问他们的网站(https://vuejs.org/)。 vue-stark-boil 样板文件支持各种功能，例如连接到钱包、监听帐户更改和调用合约。

克隆项目后，确保通过在终端中运行以下命令来安装所有依赖项：

[source, bash]
----
npm install
----


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
