= Contributors Guide

The Starknet Book is an open-source Cairo/Starknet teaching curriculum written by `starknet-edu` and the Starknet community. We welcome all contributions to this repository to help enrich the Starknet community.

== Running the Book locally

Steps:
1. Clone the repository locally using `git clone https://github.com/starknet-edu/starknetbook.git`.
2. Change directory to the repository using `cd starknetbook`.
3. Install the lunr extension using `npm i @antora/lunr-extension`.
4. Run the book locally using `npx antora --fetch antora-playbook.yml`. If an error regarding a missing extension appears then install the extension using `npm i @antora/EXTENSRION` as we did with the lunr extension in step 3.

== Our Methodology

We operate and maintain this project with an issue and pull request model. We will track
the GitHub issues section https://github.com/starknet-edu/starknetbook/issues[Issues] of this repository
and contributors can submit https://github.com/starknet-edu/starknetbook/pulls[Pull
Requests] for review by the maintainers.

Your pull request will be review by the maintainers at their earliest convenience. If you have any questions, please feel free to ask in the issues section.

=== General Work-Flow

We recommend the following work-flow for contributors:

. *Find an issue* to work on and use comments to communicate your intentions and ask questions.
. *Work in a feature branch* of your personal fork (github.com/YOUR_NAME/starknetbook) of the main repository (github.com/starknet-edu/starknetbook).
. After you have implemented or resolved the issue, *create a pull-request* to merge your changes in the main repository
. Wait for the repository maintainers to *review your changes* to ensure the issue is addressed.
. If the issue is addressed the repository maintainers will *merge your pull-request*
. If you feel like your pull-request is not addressed, please feel free to *ask for clarification* in the comments section of the pull-request.

=== Helpful Article on contribution

https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/[guide]
