= Contributors Guide

The Starknet Book is an open-source Cairo/Starknet teaching curriculum written by `starknet-edu` and the Starknet community (a.k.a., the Campers). We welcome all contributions to this repository to help enrich the Starknet community.

== Our Methodology

We operate and maintain this project with an issue and pull request model. We will track
the GitHub issues section https://github.com/starknet-edu/starknetbook/issues[Issues] of this repository
and contributors can submit https://github.com/starknet-edu/starknetbook/pulls[Pull
Requests] for review by the maintainers.

Your pull request will be review by the maintainers at their earliest convenience. If you have any questions, please feel free to ask in the issues section.

=== Style Guide

* when naming a subdirectory, please use "snake_case" and not use acronyms

=== General Work-Flow

We recommend the following work-flow for contributors:

. *Find an issue* to work on and use comments to communicate your intentions and ask questions.
. *Work in a feature branch* of your personal fork (github.com/YOUR_NAME/starknetbook) of the main repository (github.com/starknet-edu/starknetbook).
. After you have implemented or resolved the issue, *create a pull-request* to merge your changes in the main repository
. Wait for the repository maintainers to *review your changes* to ensure the issue is addressed.
. If the issue is addressed the repository maintainers will *merge your pull-request*
. If you feel like your pull-request is not addressed, please feel free to *ask for clarification* in the comments section of the pull-request.

=== Helpful Article on contribution

https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/[guide]
