= Starknet Book

This repo redirects to the Starknet Book front-end (built with Antora) at https://book.starknet.io[book.starknet.io]. This repo is only for the Starknet Book's source code (text or actual code).

Do you want to...
* *read or study* the Starknet Book? Please go to *book.starknet.io*; it is more readable. 
* *contribute* to the Starknet Book (yes, please!)? This is the right place. Go the contributing section in this README.

This Book contains material for Cairo 1.x versions. If you are looking for content related to the Cairo 0.x versions, please refer to the link:https://github.com/starknet-edu/starknetbook/tree/cairo-0[cairo-0 branch].

== Contributing

There are several sections within the Chapters that require input. Your contributions are welcome, needed, and required! 🫡

Go to the section https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.md[Contributing]. There you will find instructions on how to contribute and how to run the Book locally.

Here are things you can do to help:
* At the beginning of some sections there is a message for STARKers who want to collaborate with content.
* Empty section in a Chapter? Go for it!
* Do you think the Starknet Book needs an additional section? Propose it.
* Can a section be improved? Feel free to modify it.
* Do you want to add an alternative programming language for the examples? Yes please.
* Correct the bugs if you find any.
* Please add an explanation in the exercise comments if you feel they need them.
* Add exercises that show your favorite feature of Cairo.

== Issues

If you find an issue/bug or have a feature request please submit an issue here https://github.com/starknet-edu/starknetbook/issues[Issues].

Do you have a question?
Join our https://starknet.io/discord[Discord server], register, and join channel #tutorials-support.
