= Starknet Book

The Starknet book has moved from Github to its own front end! Read it at https://book.starknet.io/[https://book.starknet.io/]

The content is still maintained here; if you want to contribute to the book, this is the right place.

== Issues

If you find an issue/bug or have a feature request please submit an issue here https://github.com/starknet-edu/basecamp/issues[Issues]

Do you have a question?
Join our https://starknet.io/discord[Discord server], register, and join channel #tutorials-support.

== Contributing

Basecamp can be improved and will evolve as Starknet matures.
Together we are setting up The Basecamp, so there are several sections within the Camps that require Camper input. Camper, your contributions are welcome and needed!
Go to the section https://github.com/starknet-edu/basecamp/blob/main/CONTRIBUTING.md[Contributing].
Here are things you can do to help:

* Empty section in a camp? Go for it!
* Do you think Basecamp needs an additional section? Propose it.
* Can a section be improved? Feel free to modify it.
* Do you want to add an alternative programming language for the examples? Yes please.
* Correct the bugs if you find any.
* Please add an explanation in the exercise comments if you feel they need them.
* Add exercises that show your favorite feature of Cairo.
