[id="turing"]

= A practically-efficient Turing-complete STARK-Friendly CPU Architecture

While this section is being built we recommend reading the video session for this chapter and the https://www.cairo-lang.org/docs/how_cairo_works/index.html[cairo-lang docs].

`Practical`: Cairo supports conditional branches, memory, function calls, and recursion

`Efficient`: Instruction Set chosen so the corresponding AIR is efficient and optimized with `builtins`

`Turing Complete`: Can simulate any Turing machine, as such supports any feasible computation

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____

