= The Starknet Book
:navtitle: Introduction

== Welcome

Welcome to the Starknet Book!

The Starknet Book is a curriculum created to teach the Cairo programming language and Starknet development. It is divided by Chapters and built by the Starknet community (you!). Finish the resume and you will conquer the Ethereum world.

== Where to start?

Everybody has different goals in their Cairo and Starknet journey.
Follow this guide to continue trough the Starknet Book;
do you...

* ...want to set up your environment?
(TODO)
* ...want to start coding scalable and descentralized smart contracts right away?
*Chapters 1 and 2*.
* ...have a hackathon next week?
*Chapters 1 and 2*.
* ...want to go deeper into Starknet's power?
*Go on to Chapters 3 - 4*.
* ...want to explore how STARKs and Cairo are created?
*Go on to Chapters 5 - 6*.

== Links

* Community: https://community.starknet.io
* Starknet Docs: https://docs.starknet.io
* Cairo Docs: https://www.cairo-lang.org/docs

== Issues

If you find an issue/bug or have a feature request please submit an issue here https://github.com/starknet-edu/starknetbook/issues[Issues]

Do you have a question?
Join our https://starknet.io/discord[Discord server], register, and join channel #tutorials-support.

== Contributing

The Starknet Book can be improved and will evolve as Starknet matures.
Together we are setting up the Starknet Book, so there are several sections within the Chapters that require community input. Your contributions are welcome and needed!
Go to the section https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.md[Contributing].
Here are things you can do to help:

* In most sections there is a message for builders who want to collaborate with content.
* Empty section in a Chapter? Go for it!
* Do you think the Starknet Book needs an additional section? Propose it.
* Can a section be improved? Feel free to modify it.
* Do you want to add an alternative programming language for the examples? Yes please.
* Correct the bugs if you find any.
* Please add an explanation in the exercise comments if you feel they need them.
* Add exercises that show your favorite feature of Cairo.
