[id="arrays"]

= Arrays, Spans and Snapshots in Cairo

====
OWNERSHIP: After completing this subchapter, we strongly recommend exploring the concept of Ownership in Cairo by referring to the https://cairo-book.github.io/ch03-00-understanding-ownership.html[Cairo Book]. Ownership is a crucial concept, inspired by and inherited from Rust, that governs resource management and prevents common programming errors such as double-free, use-after-free, and data races. Mastering the concept of Ownership in Cairo is essential for developing robust and secure smart contracts and becoming a proficient Cairo developer.
====

An array in Cairo is a collection of multiple values of the same type, stored sequentially in memory. Similar to Rust, Cairo arrays are append-only, meaning that you can only add elements to the end of an array. Once a memory slot is written to, it cannot be overwritten, but you can still read from it.

Arrays in Cairo are useful for storing and managing data that requires a fixed-size or dynamically growing data structure. 

To use arrays in Cairo, you'll need to import the `array::ArrayTrait` trait:

[source, rust]
----
use array::ArrayTrait; // import the ArrayTrait trait
----

We'll use a Pokémon example to illustrate the concepts. You can find the documented contract code in the https://github.com/starknet-edu/starknetbook/blob/main/chapters/modules/chapter_2/pages/contracts/src/pokemon_array.cairo[Book repository] at the contracts folder.

== Creating and Initializing Arrays

To create an array in Cairo, you can use the `ArrayTrait::new()` method. Arrays are mutable by default, which means you can modify their contents.

Here's an example of creating an array with Pokémon names and appending elements to it (remember the actual contract is in the https://github.com/starknet-edu/starknetbook/blob/main/chapters/book/modules/chapter_2/pages/contracts/src/pokemon_array.cairo[Book repository]):

[source, rust]
----
fn _create_pokemon_array() -> Array::<felt252> {
    let mut pokemons = ArrayTrait::new(); // create a new array of type felt252
    pokemons.append('Pikachu'); // append 'Pikachu' to the pokemons array
    pokemons.append('Charmander');
    pokemons.append('Bulbasaur');
    pokemons.append('Squirtle');
    pokemons // return the array
}
----

In this example:

* `let mut pokemons = ArrayTrait::new()` creates a new mutable array of type `felt252`.
* The `append()` method is used to add elements (Pokémon names) to the array.
* The function returns the array after appending the Pokémon names.

In the Strings chapter, we review parts of the contract dealing with short strings, e.g., `'Pikachu'`.

=== Key Concepts

* Use the `ArrayTrait` trait to work with arrays in Cairo.
* Arrays are mutable by default.
* The `append()` method is used to add elements to an array.
* Arrays can be used to store and manage collections of elements in a sequential manner.
* Arrays are append-only, meaning that you can only add elements to the end of an array.
* Arrays are indexed starting from 0.

== Removing Elements and Obtaining the Length of an Array

In Cairo, you can remove elements from the front of an array using the `pop_front()` method. This method returns an `Option` containing the removed value if the array is not empty, and `None` if the array is empty. It's important to note that elements can only be removed from the front of an array in Cairo.

To obtain the length of an array, you can use the `len()` method.

Here's an example of removing an element and obtaining the length of a Pokémon array:

[source, rust]
----
fn _pop_pokemon_array() {
    let mut pokemons: Array<felt252> = create_pokemon_array();
    assert(pokemons.len() == 4_usize, "Unexpected length");

    let first_pokemon = pokemons.pop_front().unwrap();
    assert(pokemons.len() == 3_usize, "Unexpected length");
    assert(first_pokemon == 'Pikachu', "Unexpected pokemon");
}
----

In this example:

* `pokemons.len()` is used to obtain the length of the `pokemons` array.
* `pokemons.pop_front()` is used to remove the first element (front) from the `pokemons` array.
* `unwrap()` is used to get the removed value from the `Option` returned by `pop_front()`.
* The assertions check if the array length and removed element are as expected.


== Accessing Array Elements

To access elements in an array, you can use the `get()` and `at()` methods. The `get()` method returns an `Option` that contains the value if the index is valid, and `None` if the index is out of bounds. The `at()` method directly returns the value at the specified index, but it will cause an error if the index is out of bounds.

Here's an example of accessing elements in a Pokémon array:

[source, rust]
----
fn _index_pokemon_array() {
    let mut pokemons: Array<felt252> = create_pokemon_array();

    assert(*pokemons.get(0_usize).unwrap().unbox() == 'Pikachu', "Wrong pokemon");
    assert(*pokemons.at(1_usize) == 'Charmander', "Wrong pokemon");
}
----

== Understanding Snapshots and Spans

In this chapter, we will explore the concepts of snapshots and Spans in Starknet. A `Span` is a lightweight view of an array that allows you to access the underlying data without modifying the original array. You can create a span from an array using the `span()` method. Before diving into `Span`, it's essential to understand snapshots (defined by the operator `@`), as a `Span` struct is built upon them:

[source, rust]
----
struct Span<T> {
    snapshot: @Array<T>
}
----

A `Span` of `T` values (e.g., `Span<felt252>`) is a struct with one element: a snapshot of an `Array` of the same value `T` (e.g., `Array<felt252>`).

=== Snapshots

Snapshots are a powerful feature in Cairo, providing read-only instances of an object without taking ownership when passed to a function. Every type `T` has a snapshot version `@T`, which is always droppable and duplicatable.

To create a snapshot of a value `x` of type `T`, simply use `@x`.

==== Snapshots vs. Rust References

While snapshots may appear similar to Rust references (`&`) at first glance, there are critical differences between the two:

1. **Object type**: Unlike Rust references, which are pointers, snapshots are full objects. As a result, using snapshots does not yield performance improvements associated with pointer usage.
2. **Object immutability**: When an object is modified after creating a snapshot, the snapshot remains unaffected. This behavior contrasts with Rust references, which reflect changes to the underlying object.

==== Practical Usage of Snapshots

Snapshots have various use cases, particularly when working with arrays and data structures in Cairo. Here are some practical examples of how snapshots can be beneficial:

* **Preserving original data**: When writing a function that accepts an array and returns the sum of the first two elements, you might not want to modify the original array. In this case, using a snapshot of the array as a parameter instead of the actual array allows you to preserve the original data.
* **Immutable data views**: If you take a snapshot of an array and then add a value to the original array, the snapshot will remain unaffected, maintaining the original values without the newly added value. This feature is useful when you need an immutable view of the data at a specific point in time.
* **Read-only instances**: Some functions, such as `Array::get` and `Array::at`, require a snapshot of the object instead of the object itself. By using snapshots, you can create read-only instances that do not take ownership of the object when invoking the function. This approach is helpful when you need to access data without modifying the underlying data structure.

In summary, snapshots enable developers to work with data more efficiently, offering a way to preserve original data, create immutable views, and access read-only instances without modifying the original object.

=== Spans

Spans provide a convenient way to work with arrays without modifying the original array or worrying about ownership. To use spans, you must import the `array::SpanTrait` trait:

[source, rust]
----
use array::SpanTrait;
----

Consider the following example, which demonstrates how to access elements in a Pokémon span:

[source, rust]
----
fn _index_pokemon_span() {
    let pokemons_span: Span<felt252> = create_pokemon_array().span();

    assert(*pokemons_span.get(2_usize).unwrap().unbox() == 'Bulbasaur', "Wrong pokemon");
    assert(*pokemons_span.at(3_usize) == 'Squirtle', "Wrong pokemon");
}
----

Both functions `get` and `at` from the `SpanTrait` expect the use of a snapshot. If the Pokémon contract used `pokemons.at(1_usize)` instead of a snapshot, `*pokemons.at(1_usize)`, the compiler would return an error:

[source, rust]
----
error: Plugin diagnostic: Unexpected argument type. Expected: "@core::felt252", found: "core::felt252".
 --> pokemon_array.cairo:41:40
        assert(pokemons.at(1_usize) == "Charmander", "Wrong pokemon");
                                       ^**********^
----

In this case, the `at` method expected a snapshot (`@core::felt252`) rather than the actual value (`core::felt252`).

To avoid such errors and write efficient smart contracts, Cairo developers should have a thorough understanding of ownership, which is inspired by Rust. Refer to the https://cairo-book.github.io/ch03-00-understanding-ownership.html[Cairo Book] for more information on this topic.


== Conclusion and Summary

In this chapter, we delved into the world of arrays in Cairo, using Pokémon as an example to make the concepts more approachable and fun. We've learned how to create arrays, add elements, remove elements, and obtain the length of an array. To quickly recap, here's what we covered:

* *Create an array*: Use `ArrayTrait::new()` to create a new mutable array of a specific type.
* *Add elements*: Use the `append()` method to add elements to an array. Remember, Cairo arrays are append-only.
* *Remove elements*: In Cairo, you can only remove elements from the front of an array. Use the `pop_front()` method, which returns an `Option` containing the removed value or `None` if the array is empty.
* *Obtain array length*: Use the `len()` method to get the length of an array.
* *Access elements*: Use the `get()` and `at()` methods to access elements in an array. The `get()` method returns an `Option` that contains the value if the index is valid, and `None` if the index is out of bounds. The `at()` method directly returns the value at the specified index, but it will cause an error if the index is out of bounds.

In the following subchapter we will test our assertions in the Pokemon contract by deploying it to the Starknet testnet. This is the worst way to test a contract, but it is the only way to test it with our current knowledge. In the next chapter we will review the Protostar and Cairo testing framework, which will allow us to test our contracts locally.

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

include::ROOT:partial$snippet_contributing_blurb.adoc[leveloffset=+1]
