[id="calling_invoking"]

= Deploying, Calling and Invoking Contracts

In this chapter, we'll explore how to interact with deployed Starknet contracts using _calling_ and _invoking_. We'll use the voting contract as an example.

* Calling contracts: Interacting with contract functions marked with the `#[view]` entry point. These functions do not alter the state of the network, so they don't require fees or signing. This is similar to a `call` in the Ethereum API.
* Invoking contracts: Interacting with contract functions marked with the `#[external]` entry point. These functions do alter the state of the network and require fees and signing. This is similar to a `deploy` in the Ethereum API.

== Preparing Smart Wallets for Voting

Before we can interact with the voting contract, we need to prepare the voter and admin accounts on Starknet. Each voter account must be registered and sufficiently funded for voting. For a more detailed understanding of how accounts operate with Account Abstraction, refer to the https://book.starknet.io/chapter_5/index.html[Account Abstraction] chapter.

Ensure your https://book.starknet.io/chapter_1/environment_setup.html[environment] is ready as detailed in Chapter 1.

As mentioned in the https://book.starknet.io/chapter_1/first_contract.html[first Starknet smart contract of Chapter 1], for each smart wallet we'll use, we must create a Signer within the encrypted keystore and an Account Descriptor. Let's create a smart wallet for voting in our smart contract.

Firstly, we create a signer from a private key:

[source,bash]
----
starkli signer keystore from-key ~/.starkli-wallets/deployer/account0_keystore.json
----

Then, we create the Account Descriptor:

[source,bash]
----
touch ~/.starkli-wallets/deployer/account0_account.json
----

The Account Descriptor will look something like this:

[source,bash]
----
{
  "version": 1,
  "variant": {
        "type": "open_zeppelin",
        "version": 1,
        "public_key": "<SMART_WALLET_PUBLIC_KEY>"
  },
    "deployment": {
        "status": "deployed",
        "class_hash": "<SMART_WALLET_CLASS_HASH>",
        "address": "<SMART_WALLET_ADDRESS>"
  }
}
----

You can retrieve the smart wallet class hash with:

[source,bash]
----
starkli class-hash-at <SMART_WALLET_ADDRESS>
----

Define environmental variables for convenience:

[source,bash]
----
export STARKNET_ACCOUNT=~/.starkli-wallets/deployer/account0_account.json
export STARKNET_KEYSTORE=~/.starkli-wallets/deployer/account0_keystore.json
----

This process is identical for account1 in case you want to have a second voter.

== Contract Deployment

Before deploying, we need to declare the contract. However, if the contract is already declared (Class Hash: 0x06974677a079b7edfadcd70aa4d12aac0263a4cda379009fca125e0ab1a9ba52), you can skip this step. If you attempt to declare a previously declared contract, you'll receive a warning. But, for reference, here is the declaration command:

[source,bash]
----
starkli declare target/dev/starknetbook_chapter_2_Vote.sierra --compiler-version=2.0.1
----

Wait for L2 confirmation of the transaction. You can check the status of the transaction on a block explorer such as https://testnet.starkscan.co/[Starkscan] or https://goerli.voyager.online/[Voyager]. The confirmation typically takes a few seconds.

The following command deploys the voting contract and registers voter_0, voter_1, and voter_2 as eligible voters. These are the constructor arguments, so add a voter account that you can later vote with.

[source,bash]
----
starknet deploy 0x06974677a079b7edfadcd70aa4d12aac0263a4cda379009fca125e0ab1a9ba52 <voter_0_address> <voter_1_address> <voter_2_address>
----

An example command:

[source,bash]
----
starkli deploy 0x06974677a079b7edfadcd70aa4d12aac0263a4cda379009fca125e0ab1a9ba52 0x06dcb489c1a93069f469746ef35312d6a3b9e56ccad7f21f0b69eb799d6d2821 0x02cdAb749380950e7a7c0deFf5ea8eDD716fEb3a2952aDd4E5659655077B8510 0x053fd3749380950e7a7c0deFf5ea8eDD716fEb3a2952aDd4E5659655077B8321
----

The contract has been deployed at address: 0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf. You can find it https://goerli.voyager.online/contract/0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf[on any block explorer].

== Voter Eligibility Verification

In our voting contract, we have two functions to validate voter eligibility, `voter_can_vote` and `is_voter_registered`. These are read external functions, which means they don't alter the state of the contract but only read the current state.

The `is_voter_registered` function checks whether a particular address is registered as an eligible voter in the contract. The `voter_can_vote` function, on the other hand, checks whether the voter at a specific address is currently eligible to vote, i.e., they are registered and haven't voted already.

You can call these functions using the `starkli call` command:

[source,bash]
----
starkli call 0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf voter_can_vote 0x06dcb489c1a93069f469746ef35312d6a3b9e56ccad7f21f0b69eb799d6d2821
----

Since we provided a registered voter address as an input, the result is 1 (boolean true), indicating the voter is eligible to vote.

Next, let's call the `is_voter_registered` function using an unregistered account address to observe the output:

[source, bash]
----
starkli call 0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf is_voter_registered 0x027f4989d3cbf1654bc95f3e0083bb4542634c7cc8c7c406f17a4335fa5860a9
----

With an unregistered account address, the terminal output is 0 (i.e., false), confirming that the account is not eligible to vote.

== Casting a Vote

Now that we have established how to verify voter eligibility, we can vote! To vote, we interact with the `vote` function, which is flagged as external, necessitating the use of the `starknet invoke` command.

The `invoke` command syntax resembles the `call` command, but for voting, we submit either 1 (for Yes) or 0 (for No) as our input.

[source,bash]
----
//Voting Yes
starkli invoke 0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf vote 1

//Voting No
starkli invoke 0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf vote 0
----

Remember to cast your vote from the `voter_1` account to proceed to the subsequent step.

== Visualizing Vote Outcomes

To examine the voting results, we invoke the `get_vote_results` function, another view function, through the `starknet call` command.

[source,bash]
----
starkli call 0x0447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf get_vote_status

//Example output if one voted Yes
1 0 100 0

//Example output if 2 votes Yes and 1 voted No
2 1 66 33
----

The output reveals the tally of "Yes" and "No" votes along with their relative percentages.

Recall that we implemented a safeguard against duplicate votes. Attempt voting with a smart wallet that has already been used for voting, and you'll be met with an error:

[source,bash]
----
Error in the called contract (0x447025aad44c69080e821ffef78f03b520393acf20179a7acc23b4c696494bf):
Execution was reverted; failure reason: [0x555345525f414c52454144595f564f544544]. (TransactionFailed)
----

The string `0x555345525f414c52454144595f564f544544` is a felt252 value in Cairo, which translates to a short string. Using a tool such as the https://www.stark-utils.xyz/converter[Stark Utils] converter, we find that it corresponds to "USER_ALREADY_VOTED".

Bravo! You have now successfully deployed and interacted with a StarkNet voting smart contract!

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____

