[id="event"]

= Events in Starknet Contracts

In this chapter, we will focus on events in a Starknet contract, using an extended version of the voting contract as an example. Events are a useful tool for logging and notifying external entities about specific occurrences within a contract. They emit data that can be accessed by clients.

== Defining Events

To define an event in a Starknet contract, you can use the **`#[event]`** attribute followed by the event definition. In our extended voting contract, we have two events, **`VoteCast`** and **`UnauthorizedAttempt`**.

The **`VoteCast`** event is emitted when a vote is cast. The event takes two parameters: the voter's address and the vote value (0 for No, 1 for Yes).

[source,rust]
----
[derive(Drop, starknet::Event)]
struct VoteCast {
    voter: ContractAddress,
    vote: u8,
}
----

The **`UnauthorizedAttempt`** event is emitted when an unauthorized attempt to vote is detected. The event takes one parameter: the address of the unauthorized caller.

[source,rust]
----
#[derive(Drop, starknet::Event)]
struct UnauthorizedAttempt {
unauthorized_address: ContractAddress,
}
----

== Emitting Events

To emit an event, simply call the **`emit`** method with the appropriate event structure as an argument.

In our voting contract, the **`VoteCast`** event is emitted after the vote has been processed in the **`vote`** function.

[source,rust]
----
// Emit the VoteCast event after the vote has been processed
self.emit(VoteCast { voter: caller, vote: vote, });
----

Similarly, the **`UnauthorizedAttempt`** event is emitted if an unauthorized attempt to vote is detected.

[source,rust]
----
// Emit the UnauthorizedAttempt event after detecting an unauthorized attempt to vote
self.emit(UnauthorizedAttempt { unauthorized_address: address, });
----

Events in Starknet contracts are not directly readable from within the contract itself. Instead, events are designed to be consumed by external off-chain entities, such as clients or other services that are listening to the contract.

To get the value from an event, you need to set up an off-chain service or client to listen for the event emitted by the contract. This can be achieved using SDKs. For example, the Starknet SDK for Python provides a **`listen_for_event`** function that can be used to listen for events emitted by a contract. In following sections, we will see how to use Starknet SDKs to listen for events emitted by our voting contract."

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
