[id="scarb"]

= Scarb and the Structure of a Cairo Project

Scarb is the Cairo package manager specifically created to streamline your Cairo and Starknet development process. This powerhouse of a tool is capable of managing project dependencies, compiling projects (both pure Cairo and Starknet contracts), downloading the necessary libraries, building these libraries, and even integrating seamlessly with other essential development tools such as Protostar. 

== Integrating Scarb into Your Development Workflow

Scarb offers flexibility and convenience for your Cairo development workflow. The steps below illustrate a typical workflow in developing a Starknet contract using Scarb:

1. **Initializing the Project:** Start by running `scarb new` to create a new project. This command will automatically generate the project's basic structure, including a `Scarb.toml` configuration file and an initial `src/lib.cairo` file.

2. **Developing the Contract:** Write your Cairo code and store it in the `src` directory.

3. **Managing Dependencies:** If your contract depends on external libraries, use `scarb add` to effortlessly include these dependencies in your project.

4. **Compiling the Contract:** Run `scarb build` to compile your contract into Sierra code. This resulting code can then be examined further, or used as input for other tools or processes.

5. **Automating Tasks with Custom Scripts:** Take advantage of the `[scripts]` feature in `Scarb.toml` to define custom scripts that automate common tasks or consolidate multiple commands into a single command.

By integrating Scarb into your workflow, you leverage its features to make your development process more efficient and manageable.

== Getting Started with Scarb

To begin using Scarb, you'll first need a Git executable available in the `PATH` environment; it will be created automatically.

=== Installation

Scarb is compatible with macOS, Linux, and Windows operating systems. 

==== macOS and Linux

For macOS and Linux users, open your terminal and execute the following command:

[source, bash]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

If you wish to install a specific version of Scarb, such as a preview version, use this command instead:

[source, bash]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v 0.2.0-alpha.2
----

==== Windows

Scarb's installation on Windows requires manual setup. Follow the steps below to install Scarb on Windows:

- Download the release archive matching your operating system and CPU architecture from the https://docs.swmansion.com/scarb/download[official Scarb website] or the https://github.com/software-mansion/scarb/releases/[Scarb Github repository]. Make sure to select the most recent version.
- Extract the downloaded file to your desired location, for instance, `%LOCALAPPDATA%\Programs\scarb`.
- Add the path to the `scarb/bin` directory to your `PATH` environment variable.
- Confirm the installation by running `scarb --version` in a new terminal. The output should indicate both the Scarb and Cairo language versions.

[source, bash]
----
$ scarb --version
scarb 0.3.0 (182a9019d 2023-05-29)
cairo: 1.1.0 (https://crates.io/crates/cairo-lang-compiler/1.1.0)
----

If you encounter any issues with Scarb, please open an issue on the starknetbook repository.

== Structure of a Cairo Project

A Cairo project includes several crucial components that help create and manage a smart contract. Let's explore each part in detail.

=== Cairo Packages

Cairo packages, also referred to as "crates" in some contexts, are the building blocks of a Cairo project. Each package must follow several rules:

* A package must include a `Scarb.toml` file, which is Scarb's manifest file. It contains the dependencies for your package.
* A package must include a `src/lib.cairo` file, which is the root of the package tree. It allows you to define functions and declare used modules.

Package structures might look like the following:

[source,bash]
----
my_package/
├── src/
│   ├── module1.cairo
│   ├── module2.cairo
│   └── lib.cairo
└── Scarb.toml
----

Within the `Scarb.toml` file, you might have:

[source,toml]
----
[package]
name = "my_package"
version = "0.1.0"

[dependencies]
other_package = { path = "../other_package" }
----

=== Setting Up a Project with Scarb

To create a new project using Scarb, navigate to your desired project directory and execute the following command:

[source, bash]
----
$ scarb new hello_scarb
----

This command will create a new project directory named `hello_scarb`, including a `Scarb.toml` file, a `src` directory with a `lib.cairo` file inside, and initialize a new Git repository with a `.gitignore` file.

[source, bash]
----
hello_scarb/
├── src/
│   └── lib.cairo  
└── Scarb.toml
----

Upon opening `Scarb.toml` in a text editor, you should see something similar to the code snippet below:

[source, bash]
----
[package]
name = "hello_scarb"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[dependencies]
# foo = { path = "vendor/foo" }
----

=== Understanding Scarb.toml

The `Scarb.toml` file uses [TOML](https://toml.io/en/), an easy-to-read configuration format.

* `[package]`: This section carries information about your project.
    ** `name`, `version`: These keys set your program's name and the Scarb version to use for compilation.
* `[dependencies]`: This section is designed for listing your project’s dependencies.


=== Building a Scarb Project

Clear all content in `src/lib.cairo` and replace with the following:

[source, rust]
----
// src/lib.cairo
mod hello_scarb;
----

Next, create a new file titled `src/hello_scarb.cairo` and add the following:

[source, rust]
----
// src/hello_scarb.cairo
use debug::PrintTrait;
fn main() {
    'Hello, Scarb!'.print();
}
----

In this instance, the `lib.cairo` file contains a module declaration referencing 'hello_scarb', which includes the 'hello_scarb.cairo' file's implementation. For more on modules, imports, and the `lib.cairo` file, please refer to the subchapter on imports in Chapter 2.

Scarb mandates that your source files be located within the `src` directory, while the top-level project directory is designated for README files, license information, configuration files, and any other non-code content.

To build your project from your `hello_scarb` directory, use the following command:

[source, bash]
----
$ scarb build

Compiling hello_scarb v0.1.0 (file:///projects/Scarb.toml)
Finished release target(s) in 0 seconds
----

This command compiles your project and produces the Sierra code in the `target/dev/hello_scarb.sierra` file. Sierra serves as an intermediate layer between high-level Cairo and compilation targets such as Cairo Assembly (CASM). To understand more about Sierra, check out this https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-7f32808421f5/[article].

To remove the build artifacts and delete the target directory, use the `scarb clean` command.

Optionally, you can specify a build profile with the `--profile` or `-P` flag. For instance, to build in the release profile, use the following command:

[source, bash]
----
scarb --profile release build
----

The resulting Sierra code file will be located in the `target/release/` directory.

To run your Cairo program, execute the following command:

[source, bash]
----
$ cairo-run src/lib.cairo
[DEBUG] Hello, Scarb!                   (raw: 5735816763073854913753904210465)
Run completed successfully, returning []
----

In case you encounter this error:

[source,bash]
----
error: Found argument 'src/lib.cairo' which wasn't expected, or isn't valid in this context

Usage: cairo-run [OPTIONS] --path <PATH>
----

You need to have Cairo version alpha.7 installed. Check out this https://cairo-book.github.io/ch01-01-installation.html/[guide] for installation instructions.

Alternatively, you could try running:

[source, bash]
----
$ cairo-run --path src/lib.cairo
----

=== Defining Custom Scripts

Scarb scripts can be defined in the `Scarb.toml` file, which can then be utilized to execute custom shell scripts. You can add the following line to your `Scarb.toml` file:

[source, toml]
----
[scripts]
run-lib = "cairo-run src/lib.cairo"
----

Now, running the command `scarb run run-lib` will output

[source, bash]
----
[DEBUG] Hello, Scarb!      (raw: 5735816763073854913753904210465)

Run completed successfully, returning []
----

Using `scarb run` offers a convenient method for executing custom shell scripts. This can be extremely useful for running files and testing your project.

=== Adding Dependencies

Scarb facilitates the seamless management of dependencies for your Cairo packages. Here are two methods to add dependencies to your project:

* Edit Scarb.toml File

Open the Scarb.toml file in your project directory and locate the `[dependencies]` section. If it doesn't exist, add it. To include a dependency hosted on a Git repository, use the following format:

[source, toml]
----
[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
----

For consistency, it's recommended to pin Git dependencies to specific commits. This can be done by adding the `rev` field with the commit hash:

[source, toml]
----
[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "81bb93c" }
----

After adding the dependency, remember to save the file.

* Use the scarb add Command

Alternatively, you can use the `scarb add` command to add dependencies to your project. Open your terminal and execute the following command:

[source, bash]
----
$ scarb add alexandria_math --git https://github.com/keep-starknet-strange/alexandria.git
----

This command will add the alexandria_math dependency from the specified Git repository to your project.

To remove a dependency, you can use the `scarb rm` command.

Once a dependency is added, the Scarb.toml file will be automatically updated with the new dependency information.

=== Using Dependencies in Your Code

After dependencies are added to your project, you can start utilizing them in your Cairo code.

For example, let’s assume you have added the alexandria_math dependency. Now, you can import and utilize functions from the alexandria_math library in your `src/hello_scarb.cairo` file:

[source, rust]
----
// src/hello_scarb.cairo
use alexandria_math::fibonacci;

fn main() -> felt252 {
    fibonacci::fib(0, 1, 10)
}
----

In the above example, we import the fibonacci function from the alexandria_math library and utilize it in the main function.

=== Recap

Let's recap what we've learned about Scarb:

* The `scarb new` command can be used to create a new project.
* The `scarb build` command can be used to build a project and generate the compiled Sierra code.
* Custom scripts can be defined in the `Scarb.toml` file and executed using the `scarb run` command.
* Dependencies for our Cairo packages can be managed easily.

We've covered the basics of the Scarb package manager and its role in the Starknet ecosystem. By integrating Scarb into your workflow, you can take advantage of its powerful features to simplify and streamline your Cairo development process.

== Scarb Cheat Sheet

Here's a quick cheat sheet of some of the most commonly used Scarb commands:

* `scarb new <project_name>`: Initialize a new project with the given project name.
* `scarb build`: Compile your Cairo code into Sierra code.
* `scarb add <dependency> --git <repository>`: Add a dependency to your project from a specified Git repository.
* `scarb rm <dependency>`: Remove a dependency from your project.
* `scarb run <script>`: Run a custom script defined in your `Scarb.toml` file.

Scarb is a versatile tool, and this is just the beginning of what you can achieve with it. As you gain more experience in the Cairo language and the Starknet platform, you'll discover how much more you can do with Scarb.

To stay updated on Scarb and its features, be sure to check the https://docs.swmansion.com/scarb/docs/[official Scarb documentation] regularly. Happy coding!


[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
