[id="scarb"]

= Scarb

Scarb is the Cairo package manager designed to manage your dependencies, compile your project (either pure Cairo or Starknet contracts), download libraries your code depends on, build those libraries and integrating with other development tools, such as Protostar, making it an essential tool for Cairo developers.

== Requirements

Currently, Scarb requires a Git executable to be available in the `PATH` environment.

=== Installation

Scarb supports macOS, Linux, and Windows operating systems. 

==== macOS and Linux

To install Scarb on macOS and Linux, open your terminal and run the following command:

[source, bash]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

If you want to install a specific version of Scarb, such as a preview version, you can use the following command:

[source, bash]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v 0.2.0-alpha.2
----

==== Windows

On Windows, Scarb requires manual installation. Here are the steps to install Scarb on Windows:

- Download the release archive matching your operating system and CPU architecture from https://docs.swmansion.com/scarb/download[official Scarb website] or https://github.com/software-mansion/scarb/releases/[Scarb Github]; make sure to choose the latest version.
- The file is a compressed archive. Extract it to a location where you would like to have Scarb installed, e.g. `%LOCALAPPDATA%\Programs\scarb`.
- Add the path to the `scarb/bin` directory to your `PATH` environment variable.
- Verify the installation by running the following command in a new terminal. It should output both Scarb and Cairo language versions.


[source, bash]
----
$ scarb --version
scarb 0.2.1 (9e3c8d97d 2023-05-23)
cairo: 1.0.0 (https://crates.io/crates/cairo-lang-compiler/1.0.0)
----

If you have issues with Scarb, let us know by creating an issue on the starknetbook repository.


=== Creating a Project with Scarb

To create a new project using Scarb, navigate to your project directory and run the following command:

[source, bash]
----
$ scarb new hello_scarb
----

This command creates a new project directory named `hello_scarb` with generated project files, including a `Scarb.toml` file and an `src` directory with a `lib.cairo` file inside. A new Git repository with a `.gitignore` file is also initialized.

[source, bash]
----
hello_scarb/
├── src/
│   └── lib.cairo  
└── Scarb.toml
----

Open `Scarb.toml` in your text editor. It should look similar to the code below:

[source, bash]
----
[package]
name = "hello_scarb"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[dependencies]
# foo = { path = "vendor/foo" }
----

=== Understanding Scarb.toml

This file uses the [TOML](https://toml.io/en/) (Tom’s Obvious, Minimal Language) format, which is Scarb’s configuration format.

* `[package]`: This section indicates information about the project itself.
    ** `name`, `version`: These keys set the configuration information Scarb needs to compile your program: the name and the version of Scarb to use.
* `[dependencies]`: This section is for listing your project’s dependencies.

=== Building a Scarb Project

Delete all content in `src/lib.cairo` and add the code below:

[source, rust]
----
// src/lib.cairo
mod hello_scarb;
----

Create a new file called `src/hello_scarb.cairo` and add the code below:

[source, rust]
----
// src/hello_scarb.cairo
use debug::PrintTrait;
fn main() {
    "Hello, Scarb!".print();
}
----

The `lib.cairo` file contains a module declaration referencing `hello_scarb`, which contains the implementation of the `hello_scarb.cairo` file. To learn more about modules, imports and the `lib.cairo` file, check out the subchapter on imports in Chapter 2.

Scarb requires your source files to be located within the `src` directory. The top-level project directory is reserved for README files, license information, configuration files, and any other non-code-related content.

From your `hello_scarb` (the main) directory, build your project with the following command:

[source, bash]
----
$ scarb build

Compiling hello_scarb v0.1.0 (file:///projects/Scarb.toml)
Finished release target(s) in 0 seconds
----

This command will compile your project and generate the Sierra code in the target/dev/hello_scarb.sierra file, https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-7f32808421f5/[Sierra] is an intermediate layer between the high-level Cairo and compilation targets such as Cairo Assembly (CASM).

To clean the build artifacts and remove the target directory, you can use the scarb clean command.

You can also specify a build profile using the --profile or -P flag. For example, to build in the release profile, use the following command:

[source, bash]
----
scarb --profile release build
----

The Sierra code file will be in the target/release/ directory.

To run the Cairo program, use the following command:

[source, bash]
----
$ cairo-run src/lib.cairo
[DEBUG] Hello, Scarb!                   (raw: 5735816763073854913753904210465)
Run completed successfully, returning []
----

If you get the error:

[source,bash]
----
error: Found argument 'src/lib.cairo' which wasn't expected, or isn't valid in this context

Usage: cairo-run [OPTIONS] --path <PATH>
----

This means you have to install the Cairo version alpha.7, https://cairo-book.github.io/ch01-01-installation.html/[check out this guide to install it]

An alternative approach is to run:

[source, bash]
----
$ cairo-run --path src/lib.cairo
----

=== Defining Custom Script

We can define Scarb scripts in `Scarb.toml` file, which can be used to execute custom shell scripts. Add the following line to your `Scarb.toml` file:

[source, toml]
----
[scripts]
run-lib = "cairo-run src/lib.cairo"
----

Now, run the command `scarb run run-lib` which outputs

[source, bash]
----
[DEBUG] Hello, Scarb!      (raw: 5735816763073854913753904210465)

Run completed successfully, returning []
----

Using `scarb run` is a convenient way to run custom shell scripts that can be useful to run files and test your project

=== Adding Dependencies

Scarb allows you to easily manage dependencies for your Cairo packages. Here are two ways to add dependencies to your project.

1. Edit Scarb.toml File

Open the Scarb.toml file in your project directory and locate the [dependencies] section. If the section doesn't exist, add it. To add a dependency hosted on a Git repository, use the following syntax:

[source, toml]
----
[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
----

It is recommended to pin Git dependencies to specific commits to ensure consistency. You can achieve this by adding the rev field with the commit hash:

[source, toml]
----
[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "81bb93c" }
----

Save the file after adding the dependency.

2. Using the scarb add Command

Alternatively, you can use the scarb add command to add dependencies to your project. Open your terminal and run the following command:

[source, bash]
----
$ scarb add alexandria_math --git https://github.com/keep-starknet-strange/alexandria.git
----

This command adds the alexandria_math dependency from the specified Git repository to your project.

To remove a dependency, you can use the `scarb rm command`.

After adding a dependency, the Scarb.toml file will be updated with the new dependency information.

=== Using Dependencies in Your Code

Once you have added dependencies to your project, you can start using them in your Cairo code.

For example, let’s assume you have added the alexandria_math dependency. You can now import and use functions from the alexandria_math library in your `src/hello_scarb.cairo` file:

[source, rust]
----
// src/hello_scarb.cairo
use debug::PrintTrait;

fn main() -> felt252 {
    fibonacci::fib(0, 1, 10)
}
----

In the above example, we import the fibonacci function from the alexandria_math library and use it in the main function.

=== Recap

Let’s review what we have learned about Scarb:

* We can create a project using `scarb new`.
* We can build a project using `scarb build` to generate the compiled Sierra code.
* We can define custom scripts in `Scarb.toml` and call them with the `scarb run` command.
* We can manage dependencies for our Cairo packages easily.

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
