[id="storage"]

= Storage in Cairo

The "Storage" section in a Starknet contract defines the persistent data that will be stored on the blockchain and accessible by the contract functions. This data represents the state of the contract and can be manipulated throughout the contract's lifecycle.

In Starknet, you define a struct and annotate it with **`#[storage]`** to represent the contract's storage. The struct can contain scalar types like **`u8`** or **`felt252`**, as well as collections like **`LegacyMap`**.

The **`LegacyMap`** in Starknet is similar to a mapping in Solidity, allowing you to associate keys with values. However, unlike Solidity where you use the **`mapping`** keyword to declare a mapping, in Starknet you declare it within a struct and use the **`LegacyMap`** type.

Here's the storage struct for the Vote contract:

[source,rust]
```
#[storage]
struct Storage {
    yes_votes: u8,
    no_votes: u8,
    can_vote: LegacyMap::<ContractAddress, bool>,
    registered_voter: LegacyMap::<ContractAddress, bool>,
}
```

In this struct:

- **`yes_votes`** and **`no_votes`** are **`u8`** (unsigned 8-bit integer) variables to store the number of yes and no votes respectively.
- **`can_vote`** and **`registered_voter`** are **`LegacyMap`**s that map each registered voter's **`ContractAddress`** to a **`bool`** value. For **`can_vote`**, the **`bool`** value indicates whether the voter is allowed to vote (true) or not (false). For **`registered_voter`**, it represents whether the voter is registered (true) or not (false).

To read and write to the storage, you use the read and write methods on the `self` variable, which is a reference to the contract state.

For instance, to check if a voter is registered, you can do (note the double parentheses):

[source,rust]
```
let is_voter: bool = self.registered_voter.read((address));
```

To register a voter, you can do (no need for double parentheses):

[source,rust]
```
self.registered_voter.write(voter_address, true);
```

Here are some key points about how Cairo for Starknet handles storage:

1. Cairo uses a **`struct`** to define the storage, unlike Solidity which uses state variables and mappings directly within the contract.
2. Cairo employs the **`LegacyMap`** type to create a mapping, while Solidity uses the **`mapping`** keyword.
3. Cairo accesses storage fields using the **`read`** and **`write`** methods on the storage variable. In contrast, Solidity uses assignment and indexing to access storage fields.
4. Variables in Starknet are stored in memory according to their name rather than their type or their order of declaration. For more details, please refer to the **[https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-storage/[Starknet](https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-storage/%5BStarknet)** documentation].


[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

include::ROOT:partial$snippet_contributing_blurb.adoc[leveloffset=+1]