[id="IntroToAA"]

= Introduction to Account Abstraction

Account abstraction is a new paradigm to make blockchain accounts programmable.
Account asbtraction was introduced to solve several user onboarding and wallet interaction problems by allowing users to flexibly program more security and better user experiences into their accounts.

The idea involves interacting with the blockchain using smart contract wallets, either natively supported as part of the existing protocol or via an add-on transaction network.

== References
https://hackernoon.com/what-is-account-abstraction-and-why-is-everyone-talking-about-it
https://ethereum.org/en/roadmap/account-abstraction/

== Contributing
🎯 +++<strong>+++STARKer: +++</strong>+++ This book is an open source effort, made possible only by contributions from readers like you. If you are interested in making this resource better for other users - please suggest a change by following the instructions https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[here].
🎯