[id="WhatIsAA"]

= What is Account Abstraction?

== Account Abstraction - Definition(s)

Let us take a quick look at some popular definition(s) of account abstraction.

____
Definition 1: AA is when a *smart contract can pay for its own transactions* (https://www.youtube.com/watch?v=Osc_gwNW3Fw[Martin Triay, Devcon 6]).
In other words, abstract contracts (or account smart contracts) can pay for transactions.
Note, it is not the same as Externally Owned Accounts or Smart Wallets.
____

____
Definition 2: AA is *validation abstraction*.
In L1 there is only one way to validate transactions (retrieve an address from a signature, look at that address in the state, determine if the nonce is OK for the transaction that was sent and if the account has enough balance to perform the transaction).
With AA, you *abstract the validation process*: use different types of signatures, cryptographic primitives, execution processes, etc.
(https://app.devcon.org/schedule/9mvqce[lightclient, Devcon 6]).
____

_*Note: In computing, the term abstraction is used to generalize something.
In this case, we are generalizing smart contracts: from the existence of Externally Owned Contracts (EOA) and Contract Accounts (CA) to simply smart contracts._

== So what?

According to:

* Martin Triay (Open Zepellin), AA means https://www.youtube.com/watch?v=Osc_gwNW3Fw[huge improvements in onboarding, user experience, and security].
AA is the future of crypto UX and security.
* Julien Niset (Argent), AA means scaling self-custody which is https://www.youtube.com/watch?v=OwppworJGzs[a requirement for onboarding the next billion users].
* Vitalik, https://app.devcon.org/schedule/9mvqce[smart wallets should be the default] and AA is the key step.
* Yoav (Ethereum Foundation), https://app.devcon.org/schedule/9mvqce[AA is key security].

== Use cases (some of them, invent one!)

AA promises to put programmability into every Ethereum wallet, and unlock new frontiers for both developers and users (https://app.devcon.org/schedule/9mvqce[AA Panel, Devcon 6]).

Among other things, AA allows:

* https://medium.com/@starkware/how-starknet-is-revolutionizing-crypto-signing-ba3724077a79[Hardware Signer]: Sign transactions and messages on Braavos wallet using your biometric identity, with a key that is generated and protected by your iPhone/Android secure enclave.
* Social recovery: In case a user's private key is lost or compromised, AA allows wallets to add mechanisms to securely replace the key controlling the account.
Never worry about seed phrases again (https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/[Julien Niset, 2022])!
* Key rotation: If your keys are compromised, instead of moving all the assets, you can rotate the keys and that is it.
(XXX look more about this)
* Session keys: Signing with your face or finger to your cellphone or your favorite apps is possible with AA. Session keys are a set of permissions given to a website so, for example, you can sign in once and then the website can act on our behalf without you having to sign each time for each transaction. This is Web2 experience.
* Guardians
* Custom transaction validation schemes.
 ** Different signature schemes: You can use Ethereum signatures, Bitcoin signatures, both if you want.
The user could prefer a more gas-efficient signature, or a quantum-resistant one.
Use the secure enclave of iOS and Android devices to turn every phone into a hardware wallet (https://www.youtube.com/watch?v=Osc_gwNW3Fw[Martin Triay (Devcon 6)], https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/[Julien (2022)]).
 ** Multisignature: Change who can sign each week.
Support fraud monitoring;
inspect every transaction to make sure it complies to defined security rules, and prevent users from sending assets to a scam address or incorrect contract.
(https://www.youtube.com/watch?v=Osc_gwNW3Fw[Martin Triay (Devcon 6)], https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction[Julien (2022)]).

These are just some ideas.
More is still to come.

== Security

There are many ways AA helps security in Ethereum.
The following were mentioned by https://app.devcon.org/schedule/9mvqce[Yoav at Devcon 6]:

* Key management: Being able to add devices to your wallet so your wallet is not associated with the seed phrase, but if you lose your phone you can access it with your computer. This improves security,
* Different signature and validation schemes: You could, for example, spend small amounts freely but if you are sending a large amount the dapp or the wallet could ask for another type of signature similar to the 2 Factor Authorization. This is common in centralized exchanges. 
* Different security policies for different types of users: With EOAs (L1) we only have a single policy; if you have the key then you can do anything, else without the key you can't do anything. With AA, for example, we could create a security scheme for enterprise accounts and another one for individual users. Again, copy good practices in the banking and web2 sector.
* Different security policies for different devices: For example, a phone can send a maximum amount of tokens and for a computer, there is a limit unless you validate in some way (2FA). For this to happen we need to be able to implement different signature schemes according to each device (e.g., a computer does not use the same curve as an android phone). The EOAs support only a type of curve that is incompatible with most devices. With AA you can use several devices with the same account. Users will no longer have a different wallet on each device; one for the computer, one for the phone, and one for the Ledger. 

== Why has it not been implemented in Ethereum's L1 yet?

According to Julien Niset (https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/[2022]), the key is to eliminate EOAs.
No EIP has yet addressed this.
It is understandable since this would implicate multiple changes to the heart of the protocol;
and day by day, as the value secured by Ethereum increases, implementing AA gets more difficult due to the coordination required (https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/[Julien Niset, 2022]).

If it is so important, then why does Ethereum already supports it?
This is an example of the limitations of the EVM that can be surpassed by a new Virtual Machine such as the Cairo VM.
Proposals to implement AA have been made since the early days of Ethereum and they have constantly been "repeatedly pushed back in favour of more urgent changes." (https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/[Julien Niset, 2022]).
It is uncertain whether it will be implemented in next Ethereum versions even after the Merge.

The creation of new L2 VMs focused on scalability allowed for advances in its implementation;
Starknet and ZKSync have native AA inspired by EIP4337, considered the best proposal by experts such as Argent's Julien Niset (https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/[2022]).
It seems as if key proponents of AA, like Julien, have lost hope that EOAs are eliminated and AA is implemented at the core of Ethereum;
Argent is now pushing for the widespread adoption of AA through L2s like Starknet.

== Contributing
🎯 +++<strong>+++STARKer: +++</strong>+++ This book is an open source effort, made possible only by contributions from readers like you. If you are interested in making this resource better for other users - please suggest a change by following the instructions https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[here].
🎯