[id="WhatIsAA"]

= What is Account Abstraction?

== Account Abstraction - Definition(s)

Let's explore some popular definitions of account abstraction:

____
Definition 1: Account Abstraction (AA) is when a *smart contract can pay for its own transactions* (Martin Triay, Devcon 6)[1]. In other words, abstract contracts (or account smart contracts) can pay for transactions. Note that this is not the same as Externally Owned Accounts or Smart Wallets.
____

____
Definition 2: AA is *validation abstraction*. In L1, there is only one way to validate transactions (retrieve an address from a signature, look at that address in the state, determine if the nonce is OK for the transaction that was sent, and if the account has enough balance to perform the transaction). With AA, you *abstract the validation process*: use different types of signatures, cryptographic primitives, execution processes, etc. (lightclient, Devcon 6)[3].
____

_*Note: In computing, the term abstraction is used to generalize something. In this case, we are generalizing smart contracts: from the existence of Externally Owned Contracts (EOA) and Contract Accounts (CA) to simply smart contracts._

== Application of Account Abstraction

AA aims to make self-custody more accessible and more secure by allowing for (among others):

1. Hardware Signer: Sign transactions and messages using your biometric identity, with a key generated and protected by your smartphone's secure enclave (Starkware)[4].
2. Social recovery: Securely replace the key controlling an account in case it's lost or compromised, eliminating the need for seed phrases (Julien Niset, 2022)[5].
3. Key rotation: Change the keys controlling your account if they're compromised, instead of moving all your assets.
4. Session keys: Sign in once, and allow websites to act on your behalf without requiring constant approval for transactions. This brings a more familiar web2 experience to web3 applications.
5. Custom transaction validation schemes: Choose from various signature schemes, multisignatures, and other security rules (Martin Triay, Devcon 6)[1], (Julien Niset, 2022)[5].

AA also enhances security by offering:

1. Better key management: Add devices to your wallet, allowing for access even if you lose one device. This improvement in key management enhances security (Yoav, Devcon 6)[6].
2. Different signature and validation schemes: Implement additional security measures, like 2-factor authentication, for large transactions. This enables better security by adapting to each user's specific needs (Yoav, Devcon 6)[6].
3. Custom security policies: Tailor security schemes to suit different types of users or devices, and adapt good practices from the banking and web2 sectors (Yoav, Devcon 6)[6].

In summary, AA unlocks new possibilities for developers and users in the Ethereum ecosystem, promising a more secure and user-friendly experience. By enabling various validation schemes and improved key management, AA brings the potential for wider adoption and a better user experience.

== References:

* [1] Martin Triay, Devcon 6: https://www.youtube.com/watch?v=Osc_gwNW3Fw
* [2] Julien Niset: https://www.youtube.com/watch?v=OwppworJGzs
* [3] lightclient, Devcon 6: https://app.devcon.org/schedule/9mvqce
* [4] Starkware: https://medium.com/@starkware/how-starknet-is-revolutionizing-crypto-signing-ba3724077a79
* [5] Julien Niset, 2022: https://www.argent.xyz/blog/part-2-wtf-is-account-abstraction/
