= Hello World Account Contract

In this chapter, we will explore the fundamentals of account contracts in StarkNet using an example "Hello World" account contract written in Cairo language. You can find it in the contracts directory of this chapter in the Book's repository (TODO: add link). Account contracts are a core component of StarkNet, utilizing account abstraction to manage transactions and interactions between contracts.

== External Functions

The account contract includes several external functions to handle the validation and execution of transactions. These functions are:

1. `__validate_deploy__`: Validates the deployment of the contract.
2. `__validate_declare__`: Validates the declaration of transactions using the account.
3. `__validate__`: Validates a transaction before execution.
4. `__execute__`: Executes a transaction after successful validation.

=== __validate_deploy__

This function is responsible for validating the deployment of the account contract. It returns `starknet::VALIDATED` to confirm successful validation.

[source,cairo]
----
#[external]
fn __validate_deploy__(
    class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
) -> felt252 {
    starknet::VALIDATED
}
----

=== __validate_declare__

This function enforces that transactions now require accounts to pay fees. It returns `starknet::VALIDATED` to confirm successful validation.

[source,cairo]
----
#[external]
fn __validate_declare__(class_hash: felt252) -> felt252 {
    starknet::VALIDATED
}
----

=== __validate__

This function is called by the account contract upon receiving a transaction. If the validation is successful, it returns `starknet::VALIDATED`.

[source,cairo]
----
#[external]
fn __validate__(
    contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
) -> felt252 {
    starknet::VALIDATED
}
----

=== __execute__

If the `__validate__` function is successful, this `__execute__` function will be called. It forwards the call to the target contract using `starknet::call_contract_syscall`.

[source,cairo]
----
#[external]
#[raw_output]
fn __execute__(
    contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
) -> Span::<felt252> {
    starknet::call_contract_syscall(
        address: contract_address,
        entry_point_selector: entry_point_selector,
        calldata: calldata.span()
    ).unwrap_syscall()
}
----

== Declaring and Deploying the Hello World Account Contract

The declaring and deploying process is the same as with other contracts. Before declaring and deploying the Hello World account contract, you must first have an account contract set up to manage the deployment process. To learn more about deploying an account contract, refer to the subchapter on deploying in Chapter 2 of the Book.

Remember to compile using `scarb build` (refer to the Scarb subchapter in Chapter 2 of the Book). Then follow the steps below to declare and deploy the Hello World account contract:

* Export the required environment variables:

[source,bash]
----
export STARKNET_NETWORK=alpha-goerli
export STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
----

* Declare the contract (since the contract is already declared, you can skip this step. If you want to declare it anyway, run the following command but you will receive an error):

[source,bash]
----
starknet declare --contract target/release/starknetbook_chapter_7_HelloAccount.json --account my_account --max_fee 100000000000000000
----

The class hash is: 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe

* Deploy the contract:

[source,bash]
----
starknet deploy --class_hash 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe --account my_account --max_fee 100000000000000000
----

After completing these steps, you will have successfully declared and deployed the Hello World account contract on StarkNet. https://testnet.starkscan.co/contract/0x01e6d7698ca76788c8f9c1091ec3d6d3f7167a9effe520402d832ca9894eba4a#overview[Here is a deployed version].
