= Hello World Account Contract

In this chapter, we will explore the fundamentals of account contracts in StarkNet using an example "Hello World" account contract written in Cairo language. You can find it in the contracts directory of this chapter in the Book's repository (TODO: add link).

[,Rust]
----
// Import necessary modules
#[account_contract]
mod HelloAccount {
    use starknet::ContractAddress;
    use core::felt252;
    use array::ArrayTrait;
    use array::SpanTrait;

    // Validate deployment of the contract.
    // Returns starknet::VALIDATED to confirm successful validation.
    #[external]
    fn __validate_deploy__(
        class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
    ) -> felt252 {
        starknet::VALIDATED
    }

    // Validate declaration of transactions using this Account.
    // This function enforces that transactions now require accounts to pay fees.
    // Returns starknet::VALIDATED to confirm successful validation.
    #[external]
    fn __validate_declare__(class_hash: felt252) -> felt252 {
        starknet::VALIDATED
    }

    // Validate transaction before execution.
    // This function is called by the account contract upon receiving a transaction.
    // If the validation is successful, it returns starknet::VALIDATED.
    #[external]
    fn __validate__(
        contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
    ) -> felt252 {
        starknet::VALIDATED
    }

    // Execute transaction.
    // If the '__validate__' function is successful, this '__execute__' function will be called.
    // It forwards the call to the target contract using starknet::call_contract_syscall.
    #[external]
    #[raw_output]
    fn __execute__(
        contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
    ) -> Span::<felt252> {
        starknet::call_contract_syscall(
            address: contract_address,
            entry_point_selector: entry_point_selector,
            calldata: calldata.span()
        ).unwrap_syscall()
    }
}
----

== External Functions

The account contract includes several external functions to handle the validation and execution of transactions. These functions are:

1. `__validate_deploy__`: Validates the deployment of the contract.
2. `__validate_declare__`: Validates the declaration of transactions using the account.
3. `__validate__`: Validates a transaction before execution.
4. `__execute__`: Executes a transaction after successful validation.

=== __validate_deploy__

This function is responsible for validating the deployment of the account contract. It returns `starknet::VALIDATED` to confirm successful validation.

[source,cairo]
----
#[external]
fn __validate_deploy__(
    class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
) -> felt252 {
    starknet::VALIDATED
}
----

=== __validate_declare__

This function enforces that transactions now require accounts to pay fees. It returns `starknet::VALIDATED` to confirm successful validation.

[source,cairo]
----
#[external]
fn __validate_declare__(class_hash: felt252) -> felt252 {
    starknet::VALIDATED
}
----

=== __validate__

This function is called by the account contract upon receiving a transaction. If the validation is successful, it returns `starknet::VALIDATED`.

[source,cairo]
----
#[external]
fn __validate__(
    contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
) -> felt252 {
    starknet::VALIDATED
}
----

=== __execute__

If the `__validate__` function is successful, this `__execute__` function will be called. It forwards the call to the target contract using `starknet::call_contract_syscall`.

[source,cairo]
----
#[external]
#[raw_output]
fn __execute__(
    contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array::<felt252>
) -> Span::<felt252> {
    starknet::call_contract_syscall(
        address: contract_address,
        entry_point_selector: entry_point_selector,
        calldata: calldata.span()
    ).unwrap_syscall()
}
----

== Declaring and Deploying the Hello World Account Contract

The declaring and deploying process is the same as with other contracts. Before declaring and deploying the Hello World account contract, you must first have an account contract set up to manage the deployment process. To learn more about deploying an account contract, refer to the subchapter on deploying in Chapter 2 of the Book.

Remember to compile using `scarb build` (refer to the Scarb subchapter in Chapter 2 of the Book). Then follow the steps below to declare and deploy the Hello World account contract:

* Export the required environment variables:

[source,bash]
----
export STARKNET_NETWORK=alpha-goerli
export STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
----

* Declare the contract (since the contract is already declared, you can skip this step. If you want to declare it anyway, run the following command but you will receive an error):

[source,bash]
----
starknet declare --contract target/release/starknetbook_chapter_7_HelloAccount.json --account my_account --max_fee 100000000000000000
----

The class hash is: 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe

* Deploy the contract:

[source,bash]
----
starknet deploy --class_hash 0x07e813097812d58afbb4fb015e683f2b84e4f008cbecc60fa6dece7734a2cdfe --account my_account --max_fee 100000000000000000
----

After completing these steps, you will have successfully declared and deployed the Hello World account contract on StarkNet. https://testnet.starkscan.co/contract/0x01e6d7698ca76788c8f9c1091ec3d6d3f7167a9effe520402d832ca9894eba4a#overview[Here is a deployed version].

== Summary

In this subchapter, we delved into the details of a basic account contract in StarkNet using a "Hello World" example.

We also outlined the steps to declare and deploy the Hello World account contract on the StarkNet network. The deployment process involves exporting the required environment variables, declaring the contract, and deploying it using the class hash.

As we progress in our exploration of StarkNet account contracts, the next subchapter will introduce a standard account contract, drawing parallels with the standard account contract defined by Open Zeppelin and Starkware. This will further strengthen our understanding of how account contracts operate within the StarkNet ecosystem.

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
