[id="starknet_aa"]

= Account Abstraction model in Starknet

Now that we know better the concept of AA, let's actually code it in Starknet.

== Account Contract Interface

Although account contracts are nothing more than smart contracts, they have methods that set them apart from other smart contracts. The following interface to an account contract implements the AA protocol. It has a public key associated with it and can validate and execute transactions. Here's what it does:

* `constructor`: This optional method initializes the account contract. While an account contract can exist without a constructor, it is common practice to establish the associated public key within the constructor.
* `validate_transaction`: An optional helper method, `validate_transaction`, checks the validity of a transaction. This could involve comparing a signature against an associated public key, or any other validation process as defined by the contract creator.
* `__validate_deploy__`: This method is invoked during the deployment process and serves to validate the deployment of a new contract.
* `__validate_declare__`: This method validates the declaration of a new contract. It confirms the syntax and semantics of the contract declaration are correct.
* `__validate__`: This method validates transactions before they are executed. It ensures that the transaction adheres to the rules defined in the contract.
* `__execute__`: After the transactions have been validated, `__execute__` is the method that executes a series of contract calls.

Account contracts play a vital role in ensuring the security of the Starknet network by allowing only transactions with valid signatures to be executed.

Here is a generic implementation of an account contract:

[,Rust]
----
#[account_contract]
mod Account {
    use starknet::ContractAddress;

    #[constructor]
    fn constructor(public_key_: felt252);

    fn isValidSignature() -> felt252;

    #[external]
    fn __validate_deploy__(
        class_hash: felt252, contract_address_salt: felt252, public_key_: felt252
    ) -> felt252;

    #[external]
    fn __validate_declare__(class_hash: felt252) -> felt252;

    #[external]
    fn __validate__(
        contract_address: ContractAddress, entry_point_selector: felt252, calldata: Array<felt252>
    ) -> felt252;

    #[external]
    #[raw_output]
    fn __execute__(mut calls: Array<Call>) -> Span<felt252>;
}
----

The entry points of an account contract are its callable functions. Let's explore these in detail:

* `constructor`: This function is not mandatory, but it's useful for setting up an account contract. It accepts a `public_key` parameter that represents the public key associated with the account. In the future, there may be a `setPublicKey()` method to facilitate account transfers.
* `isValidSignature`: Inspired by EIP-1271, this function returns true if a given signature is valid; otherwise, it reverts.
* `__validate__`: Allows you to define an arbitrary logic to determine if a transaction is valid or not.
They can not read This function allows you to define custom logic for determining the validity of a transaction. It cannot read other contracts' storage, which helps prevent spam. The account contract calls `__validate__` when it receives a transaction. The function takes the following arguments (calldata):
 ** `contract_address: ContractAddress`: The target contract address.
 ** `entry_point_selector: felt252`: The function to be called on the target contract.
 ** `calldata: Array<felt252>`: An array representing the function parameters.. Remember calldata are the parameters used to call a function.
* `__validate_declare__`: This function validates the signature before declaring a new contract. It takes a single argument, `class_hash`, which represents the class hash of the contract to be declared.
* `__execute__`: This function serves as the state-changing entry point for all user interactions with any contract, including managing the account contract itself. It is called after successful validation by `__validate__`. The function takes an argument `mut calls`, which is an array of `Call` structs.

== The Call Struct

The `Call` struct represents a single call to a contract:

[,Rust]
----
struct Call {
    to: ContractAddress,
    selector: felt252,
    calldata: Array<felt252>
}
----

It contains the following fields:

* `to`: The target contract address.
* `selector`: The selector of the function to be called on the target contract.
* `calldata`: An array representing the function parameters.

== Summary

In this chapter, we explored the Account Abstraction model in Starknet, focusing on account contracts and their methods.

To summarize:

* Account contracts are smart contracts implementing the Account Abstraction protocol.
* They provide methods for validating and executing transactions and contract deployments.
* They offer flexibility to users by allowing them to define custom validation logic.

In the next subchapter, we will implement a simple account contract and learn how to deploy it on Starknet. This will provide a practical understanding of how account contracts work and how to interact with them.


[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====