= Starknet Development Environment Setup

This chapter walks you through setting up your Starknet development tools.

Essential tools to install:

. link:https://github.com/xJonathanLEI/starkli[Starkli] - A CLI tool for interacting with Starknet. More tools are discussed in Chapter 2.
. link:https://github.com/software-mansion/scarb[Scarb] - Cairo's package manager that compiles code to Sierra, a mid-level language between Cairo and CASM.

[NOTE]
====
For support or queries, visit our link:https://github.com/starknet-edu/starknetbook/issues[GitHub Issues] or contact espejelomar on Telegram.
====

== Starkli Installation

Easily install Starkli using Starkliup, an installer invoked through the command line.

[source,shell]
----
curl https://get.starkli.sh | sh
starkliup
----

Restart your terminal and confirm installation:

[source,shell]
----
starkli --version
----

To upgrade Starkli, simply repeat the steps.

== Scarb Package Manager Installation

We will get deeper into Scarb in link:https://book.starknet.io/chapter_2/scarb.html[Chapter 2].

For macOS and Linux:

[source,bash]
----
curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
----

For Windows, follow manual setup in the link:https://docs.swmansion.com/scarb/download.html#windows[Scarb documentation].

Restart the terminal and run:

[source,bash]
----
scarb --version
----

To upgrade Scarb, rerun the installation command.

You are now set to code in Cairo and deploy to Starknet!


[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet!
____
