[#setup]

= Setting Up Your Starknet Development Environment

In this chapter, we guide you through setting up your development environment for Cairo and Starknet. The goal is to equip you with the tools necessary to build, deploy, and interact with Cairo smart contracts on the Starknet network. We'll be installing the Cairo compiler, a fundamental tool for this task, and the Starknet Command Line Interface (CLI), a utility to interact with the Starknet network.

. The Starknet CLI is a command-line interface that allows you to interact with Starknet. This is one of the tools that allow us to interact with Starknet, however, it is not the only one. We will cover other tools in later chapters (e.g., the Starknet JavaScript/Python/Rust SDK or Protostar).
. The Cairo compiler is a tool that compiles Cairo code to Sierra.

The setup process can be accomplished through two different methods: setting up a local development environment or using a Docker container. Both options are covered in this chapter, allowing you to choose the one that best suits your needs and preferences.

[NOTE]
====
For support or feedback regarding this critical section, please visit our https://github.com/starknet-edu/starknetbook/issues[Issues section of the Book's GitHub repository] or reach out to espejelomar directly on Telegram. 
====

== Prerequisites

Before you proceed, ensure that you have the following prerequisites installed on your system:

* https://www.python.org/downloads/release/python-390/[Python 3.9]
* https://www.rust-lang.org/tools/install[Rust]


== Starknet CLI Installation

To install the Starknet CLI, follow these steps:

* *Set up your virtual environment*:

We recommend working inside a Python virtual environment. This isolates your project's dependencies from your system's global Python installation. To create and activate a virtual environment, you can use either `venv` or `pyenv`.

a. Using `venv`:

[source, bash]
----
# Create a virtual environment named "cairo_venv"
python3.9 -m venv ~/cairo_venv
# Activate the virtual environment
source ~/cairo_venv/bin/activate
----

a. Using `pyenv`:

If you encounter any issues with missing dependencies or have problems during the installation process, please refer to the https://github.com/pyenv/pyenv/wiki#troubleshooting--faq[FAQ / Troubleshooting section] of the `pyenv` documentation.

[source, bash]
----
# Install pyenv
curl https://pyenv.run | bash

# Add the following lines to your .bashrc or .zshrc
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Restart your terminal and run the following commands
pyenv install 3.9.0
pyenv virtualenv 3.9.0 cairo_venv
pyenv activate cairo_venv
----

After creating and activating the virtual environment, you should see `(cairo_venv)` in the command line prompt, indicating that the virtual environment is active, for example:

[source, bash]
----
(cairo_venv) satoshi@nakamoto-notebook %
----

* *Install the necessary dependencies for your operating system*:

Before installing the Starknet CLI, you need to install some system-specific dependencies. Follow the instructions for your operating system:

a. Ubuntu:

[source, bash]
----
sudo apt install -y libgmp3-dev
----

a. Mac:

[source, bash]
----
brew install gmp
----

Once you have installed the system-specific dependencies, proceed with installing the Python packages required for Starknet CLI:

[source, bash]
----
pip install ecdsa fastecdsa sympy
----

These Python packages provide cryptographic and mathematical functionality needed by the Starknet CLI.

* *Install the Starknet CLI*:

Now that you have set up the environment and installed the dependencies, you can install the Starknet CLI. Follow these steps:

a. Uninstall any previous version of `cairo-lang` (`cairo-lang` is the name of the package that contains the Starknet CLI):

[source, bash]
----
pip uninstall cairo-lang
----

a. Install the latest version of `cairo-lang`:

[source, bash]
----
pip install cairo-lang
----

After you have installed the Starknet CLI, verify your installation by checking the version:

[source, bash]
----
starknet --version
----

If you get the following error:

[source, bash]
----
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
----

Try downgrading the version of urllib3:

[source, bash]
---
pip install urllib3==1.26.6 
---

Then check the version again:

[source, bash]
----
starknet --version
----

The output should show the installed version of Starknet CLI. Make sure the version matches https://github.com/starkware-libs/cairo-lang/releases[the latest release].

To upgrade to the latest version of the Starknet CLI, run the following command:
[source, bash]
----
pip install cairo-lang --upgrade  
----

[NOTE]
====
You can receive updates about the Starknet versions and releases by joining the https://airtable.com/shrFYJjlo9KCpBFMA[email list].
====

== Cairo Compiler Installation

To install the Cairo compiler, follow these steps:

* Clone the Cairo repository and set it up:

[source, bash]
----
# Go to your $HOME directory
cd ~/
# Clone the Cairo compiler repo to a folder called .cairo in your home directory
git clone https://github.com/starkware-libs/cairo/ .cairo

# Checkout the working branch and generate the release binaries
cd .cairo/

git checkout tags/v1.1.0
cargo build --all --release
----

* Add Cairo executables to your PATH:

Update your `.bashrc` or `.zshrc` file to add the Cairo binaries to your `PATH` environment variable:

[source, bash]
----
# Add the command below to your .bashrc or .zshrc
export PATH="$HOME/.cairo/target/release:$PATH"
----

Open a new shell and check that the following command returns a version number:

[source, bash]
----
cairo-compile --version
----

* To update the Cairo compiler we just need to checkout the newest tag, run the following commands:

[source, bash]
----
# Go to your Cairo cloned repo
cd ~/.cairo

# Fetch the newest tags
git fetch

# Checkout the newest tag
git checkout tags/v1.1.0
cargo build --all --release
----

Open a new shell and check that the you have the intended version:

[source, bash]
----
cairo-compile --version
----

Your local development environment for Starknet is now set up. You can now start building, deploying, and interacting with Cairo smart contracts.

== Docker Setup for Starknet Development

[NOTE]
====
If you encounter any issues or difficulties while setting up Starknet and Cairo using the Docker method, we encourage you to reach out for assistance. Please report your concerns in the https://github.com/starknet-edu/starknetbook/issues[Issues section of the Book's GitHub repository], or contact espejelomar directly on Telegram. Your feedback is invaluable for improving this critical section, which plays a key role in onboarding developers to the Starknet ecosystem.
====

Using a Docker environment for Starknet development offers several benefits compared to setting up the development environment locally. These benefits include:

- *Isolation*: Docker containers provide an isolated environment for your Starknet development, ensuring that dependencies and configurations do not interfere with other projects or your system's global settings.

- *Portability*: A Docker container can run on any system with Docker installed, allowing you to easily share your development environment with others or move it between different machines without reconfiguring the environment from scratch.

- *Reproducibility*: Docker images ensure that your development environment is consistent across different systems, helping to eliminate issues arising from differences in dependencies or configurations.

- *Versioning*: You can use different Docker images or tags for different versions of the Starknet development tools, allowing you to easily switch between versions as needed.

- *Easier management*: Docker simplifies managing development environments, allowing you to start, stop, and restart containers with ease. It also makes it easy to clean up your environment by removing containers and images.

With these benefits in mind, the following sections will guide you through setting up a Docker environment for Starknet development. This environment will allow you to easily build, deploy, and interact with Cairo smart contracts using Docker.

*Before you proceed, ensure that you have the following prerequisites installed on your system:*

- https://www.docker.com/[Docker]

=== Pulling the Docker Image

The first step is to pull the Docker image containing the necessary tools for Starknet development. Execute the following command in your terminal:

[source, bash]
----
docker pull artudev19/cairo-env:latest
----

This command downloads the Starknet Docker image.

=== Running the Docker Container

To run a container from the image, execute the `docker run` command. To make certain information persistent, use a volume by passing the flag `-v from_host_path:to_container_path`. This will reflect the content in the host_path inside the container. If you specify a path in the container that does not exist, Docker will create it automatically.

[source, bash]
----
docker run -it --name stark-env -v /Desktop/stark-apps/contracts:/contracts artudev19/cairo-env:latest
----

This command runs a container named `stark-env` (ensure your Docker daemon is running) and opens a terminal where you can execute Starknet and Cairo commands. In the example above, the Cairo contracts from your local machine will be in the `stark-app/contracts` directory, while in the container, they will be in the `contracts` path.

=== Verifying the Installation

Check the installed versions of Starknet CLI and Cairo compiler:

[source, bash]
----
starknet --version
cairo-compile --version
----

The output should show the installed version of Starknet CLI and Cairo compiler. Ensure the versions match https://github.com/starkware-libs/cairo-lang/releases[the latest release].

=== Managing the Docker Container

To start the container in the future, execute:

[source, bash]
----
docker start stark-env
----

To connect to the running container, execute:

[source, bash]
----
docker exec -it stark-env zsh
----

Your Docker development environment for Starknet is now set up. You can now start building, deploying, and interacting with Cairo smart contracts.

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____