[id="data"]

= Data Availability

The data availability problem:

* STARK proofs generate a proof of computation.
 ** ex: valid execution from genesis to block 100
* you don't need the output of the program to validate the program ran correctly
 ** ex: state of block 100
* my contract logic requires the state of block 100
 ** ex: if we don't have the state of block 100 "stored" somewhere our contract is essentially stuck

*Solution: Validity Rollup - store the state on secure L1*

* current state of Starknet
* periodically store the rollup state to Ethereum
* inherit the security of the base chain

*Solution: Validium - store data "off chain"*

* IPFS, Celestia, cloud providers
* can secure with a Data Availability Committee(DAC)
* data can be private
* less expensive

*Solution: Volition - hybrid*

* single chain can dynamically chose where data is stored
* application flexibility
* composability implications

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
