[id="decentralization"]

= Decentralization

Starknet continues to evolve, and we gradually shift our gaze towards decentralization. While we expect Starknet to be decentralized only at the end of the year, it's not too early to decide on the decentralization scheme.

While every other decentralized network has only Sequencers, Starknet has two components: Sequencers (that determine which transactions to execute) and Provers (that prove the correctness of the chosen transactions). A good decentralization approach is required to decentralize the Provers and answer questions like "`who can publish proofs`" or even "`when do we publish proofs`"? However, an approach that says: "`let's take some consensus algorithm for sequencing, and demand each sequencer to prove what he sequenced`" is too naive and creates what we refer to as the "handoff problem.`"

== Design Goals

* `Permissionlessness` - anyone can be a Sequencer or a Prover (given they invest enough resources to it).
* `Assuming rationality, not honesty` - Since anyone can participate, the protocol can't assume parties blindly follow the protocol and enforce correct behavior by explicit checks and economic incentivization.
* `Sufficiently Scalable` - the protocol should scale reasonably well, up until a point where we have a reasonably large number of participants. It's hard to determine what number is "`reasonably large.`"
* `Strong and Fast L2 Finality` - Starknet state becomes final only after a batch is proven to L1 (which might take as long as several hours today). Therefore, the L2 decentralization protocol should make meaningful commitments regarding the planned execution order well before the next batch is proved.
* `Inexpensive` - the users shouldn't pay excessively high transaction fees to sponsor the work done by the entities (Sequencers and Provers) that run the Starknet consensus protocol.
* `Lightweight` - We want to leave most of Starknet computational "`real estate`" for the applicative layer of Starknet. As an extreme counterexample, a situation where 50% of the Cairo steps proven in each block are dedicated to verifying the consensus protocol itself is wasteful and does not make sense.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
