[id="index"]

= BUIDL and Tooling

While this section is being built, we recommend reading the video session for this chapter and the https://github.com/gakonst/awesome-starknet[community resources page].

In this chapter, we will learn how to use some of the existing toolings for Cairo and Starknet. Please notice there is more tooling being developed each month; here, we will cover just a part.

We are currently able to operate with the Starknet Alpha. The recommended steps for deploying contracts are:

. Unit tests - You can use Protostar, Nile, or starknet.py.
. Devnet - Deploy in the https://github.com/Shard-Labs/starknet-devnet[Shard Lab's] `starknet-devnet`.
. Testnet - Deploy to the Goerli, `alpha-goerli`, or Goerli 2. You can use Protostar, Nile, Hardhat, and more.
. Mainnet - Deploy to Alpha Starknet, `alpha-mainnnet`. Similar to the testnet.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
