[id="verifiers_solidity"]

= Verifiers in Solidity

L1 smart contract that verifies STARK proofs from SHARP.

As discussed on the SHARP page, SHARP takes the Cairo program’s execution trace, proves that it’s valid, and sends this proof to the Verifier contract on Ethereum.

Verifier address on Ethereum mainnet: https://etherscan.io/address/0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60[0x47312450B3Ac8b5b8e247a6bB6d523e7605bDb60]

== Example of a transaction sent to Verifier contract
Let's take a look at a transaction that was sent to the Verifier contract on Ethereum mainnet. 
https://etherscan.io/tx/0xde0bcb45698e8ef67fef8bff8615715dac0cf0882a131a21273e58607330d5f9[0xde0bcb45698e8ef67fef8bff8615715dac0cf0882a131a21273e58607330d5f9]

=== Transaction trace
- Verifier contract is a proxy contract so when it's called, implementation contract is called instead. Implementation contract is GpsStatementVerifier contract https://etherscan.io/address/0x6cb3ee90c50a38a0e4662bb7e7e6e40b91361bf6[0x6cB3EE90C50a38A0e4662bB7e7E6e40B91361BF6]
- Next the GpsStatementVerifier contract executes opcode `CALL` to CpuFrilessVerifier contract https://etherscan.io/address/0xe9664d230490d5a515ef7ef30033d8075a8d0e24[0xe9664d230490d5a515ef7ef30033d8075a8d0e24]
- CpuFrilessVerifier contract executes opcode `CALL` to MemoryPageFactRegistry contract https://etherscan.io/address/0xfd14567eaf9ba941cb8c8a94eec14831ca7fd1b4[0xfd14567eaf9ba941cb8c8a94eec14831ca7fd1b4], recursively to check facts. Each call with fact as input and output true/false.

For example you can query the `isValid` function on MemoryPageFactRegistry contract https://etherscan.io/address/0xfd14567eaf9ba941cb8c8a94eec14831ca7fd1b4[0xfd14567eaf9ba941cb8c8a94eec14831ca7fd1b4] with input `0x72c8d723081b60693b32d77a369782ff189754a5897002314fb1569b7e2ee1e2` to have `true` as output.

But how MemoryPageFactRegistry contract knows that the fact is valid? 

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
