[id="WhyAA"]

= Why Account Abstraction?

== Wallets and Users
Crypto wallets are an integral part of onboarding a user to web3. However, wallets can be overwhelming and difficult to use as someone can lose a lot with one small mistake.

Let us look at a few issues with wallets as of today:
* Most Ethereum users use centralized exchanges because managing a self-custody wallet is difficult; this is not self-custody. +
* In 5 years it would be bizarre that we used to secure our assets by writing 12 words on paper. Seed phrases should be a thing of the past. +
* There is no safety net for users using wallets with self-custody. +

Let's take a quick look at how accounts work on Ethereum currently.

== Accounts on Ethereum

There are two types of accounts on Ethereum:

* *Externally Owned Accounts* (EOA) +
* *Contract Accounts* (CA).

For the rest of this article, we will refer to EOAs as accounts, as they are most relevant to this chapter. 

As the name indicates, EOAs are accounts owned by something external to the blockchain - namely, users. The state of the account on Ethereum can be modified only through transactions, which have to be initiated by an EOA(There can be contract accounts in the chain of triggering).

*Does that mean that anyone can trigger a transaction from any EOA?* No, and this is where the concept of a signer comes into the picture.

Every account on Ethereum is associated with a cryptographic object called a signer. A signer, also called a keypair, is made of two keys: a private key and a public key.

The private key, a.k.a. the secret, can be used to sign digital messages, and the public key can enable anyone to verify that a given signature was signed by its corresponding private key.

*How is an account associated with a signer?* Through the account address.

The address of an EOA is derived from the public key of a signer. More specifically, the address is the last 20 bytes of the Keccak-256 hash of the public key.

The owner of the account can thus authorize a transaction from its account by signing the parameters of the transaction with the corresponding private key.

*But what if you lose your private key?*

Because your private key is your account, losing your key means losing your account.

Even worse, if someone else has your private key they also have your account... and all the tokens it contains. And there is nothing you can do about it! Hundreds of millions of dollars, if not billions, have already been lost or stolen because of a loss or theft of private keys.

This is where *account abstraction* can help users - with possibilities like social recovery and several other cool features, account asbtraction can be the key to unlocking crypto mass adoption.

Let's learn more about it in the next chapter.

== Contributing
🎯 +++<strong>+++STARKer: +++</strong>+++ This book is an open source effort, made possible only by contributions from readers like you. If you are interested in making this resource better for other users - please suggest a change by following the instructions https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[here].
🎯