[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib/cairo-contracts/src"] 

[contracts]
vote = ["src/voting.cairo"]

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5000/"
chain-id = 1536727068981429685321