[id="explorers"]

= Block Explorers

A block explorer, or blockchain explorer, enables you to see transactions, blockchain metrics and other information.

The following block explorers provide information on StarkNet.

.StarkNet block explorers, in alphabetical order
|===
|Name|Mainnet|Goerli|Goerli 2

|Starkscan|https://starkscan.co/[Mainnet]|https://testnet.starkscan.co/[Testnet]|https://testnet-2.starkscan.co/[Testnet-2]

|Viewblock|https://viewblock.io/starknet[Mainnet]|https://viewblock.io/starknet?network=goerli[Goerli]|https://viewblock.io/starknet?network=goerli2[Goerli2]

|https://nethermind.io/voyager[Voyager]|https://voyager.online/[Mainnet]|https://goerli.voyager.online/[Goerli]|https://goerli-2.voyager.online/[Goerli2]
|===

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
