[id="memory"]

= Memory Model

== Continous
Memory addresses accessed by a program must be continuous.
For example, if addresses 7 and 9 are accessed, then 8 must also be accessed before the end of the program.
The prover will automatically fill the empty memory cells with arbitrary values.
Having such gaps is inefficient, as it means memory is being consumed without being used.
Introducing too many holes could make the generation of a proof too expensive.
However, this still does not violate the soundness guarantee -- a false proof cannot be generated regardless.
In practice we can store values in memory cells while skipping memory cells (see https://github.com/starknet-edu/starknetbook/blob/main/chapters/modules/chapter_5/pages/registers/cairo/ap_fp_example.cairo[registers/cairo/ap_fp_example.cairo]), the prover will fill the empty cells to keep the memory continous.

== Write-once, read-only
We can think of the memory of Cairo as a write-once memory (it can only be written once).
If we assign that `assert [d] = 7;` then the address `d` in memory will always contain the value `7` until the execution of our program is finished.
We won't be able to change what address `d` stores at run time, we could only write it once and then read it.

== Relative addresses
The absolute address of each memory cell can only be determined at the end of the execution of the Cairo program.
That is, we are dealing with addresses relative to other addresses.
I cannot say that I want the felt equivalent to `“I rule here”` to be found in memory cell number 32.
I can say, for example, I want the felt equivalent to `Cairo rule”` to be found in the next empty cell or in three cells from the current one being used.
Do you notice how we are not talking about absolute addresses but relative addresses?
We will review registers, which are very useful for this, in a the next section.