[id="starknet-react"]

= Starknet React: A Pathway to Robust Decentralized Applications

Authored by the https://github.com/apibara/[Apibara] team, https://github.com/apibara/starknet-react/[Starknet React] is an open-source collection of React providers and hooks meticulously designed for Starknet. Drawing inspiration from https://github.com/tmm/wagmi/[wagmi], this ingenious toolkit mimics a strikingly similar API, facilitating a smooth transition for those familiar with wagmi.

To immerse in the real-world application of Starknet React, we recommend exploring the comprehensive example dApp project at https://github.com/finiam/starknet-demo-dapp/[starknet-demo-dapp].


== Integrating Starknet React

Embarking on your Starknet React journey necessitates the incorporation of vital dependencies. Let's start by adding them to your project.

[source,shell]
----
yarn add @starknet-react/core starknet get-starknet
----

[NOTE]
====
https://www.starknetjs.com/[Starknet.js] is an essential SDK facilitating interactions with Starknet. In contrast, https://github.com/starknet-io/get-starknet/[get-starknet] is a package adept at managing wallet connections.
====

Proceed by swaddling your app within the `StarknetConfig` component. This enveloping action offers a degree of configuration, while simultaneously providing a React Context for the application beneath to utilize shared data and hooks. The `StarknetConfig` component accepts a connectors prop, allowing the definition of wallet connection options available to the user.

[source,typescript]
----
const connectors = [
  new InjectedConnector({ options: { id: "braavos" } }),
  new InjectedConnector({ options: { id: "argentX" } }),
];

return (
    <StarknetConfig
      connectors={connectors}
      autoConnect
    >
      <App />
    </StarknetConfig>
)
----

== Establishing Connection and Managing Account

Once the connectors are defined in the config, the stage is set to use a hook to access these connectors, enabling users to connect their wallets:

[source,typescript]
----
export default function Connect() {
  const { connect, connectors, disconnect } = useConnectors();

  return (
    <div>
      {connectors.map((connector) => (
        <button
          key={connector.id()}
          onClick={() => connect(connector)}
          disabled={!connector.available()}
        >
          Connect with {connector.id()}
        </button>
      ))}
    </div>
  );
}
----

Observe the `disconnect` function that terminates the connection when invoked. Post connection, access to the connected account is provided through the `useAccount` hook, offering insight into the current state of connection:

[source,typescript]
----
const { address, isConnected, isReconnecting, account } = useAccount();

return (
    <div>
      {isConnected ? (
          <p>Hello, {address}</p>          
      ) : (
        <Connect />
      )}
    </div>
);
----

The state values, such as `isConnected` and `isReconnecting`, receive automatic updates, simplifying UI conditional updates. This convenient pattern shines when dealing with asynchronous processes, as it eliminates the need to manually manage the state within your components.

Having established a connection, signing messages becomes a breeze using the account value returned from the `useAccount` hook. For a more streamlined experience, the `useSignTypedData` hook is at your disposal.

[source,typescript]
----
const { data, signTypedData } = useSignTypedData(typedMessage)  

return (
  <>
    <p>
      <button onClick={signTypedData}>Sign</button>
    </p>
    {data && <p>Signed: {JSON.stringify(data)}</p>}
  </>
)
----

Starknet React supports signing an array of `BigNumberish` values or an object. While signing an object, it is crucial to ensure that the data conforms to the EIP712 type. For a more comprehensive guide on signing, refer to the Starknet.js documentation: https://www.starknetjs.com/docs/guides/signature/[here].

== Navigating the Network

In addition to wallet and account management, Starknet React equips developers with hooks for network interactions. For instance, useBlock enables the retrieval of the latest block:

[source,typescript]
----
const { data, isError, isFetching } = useBlock({
    refetchInterval: 10_000,
    blockIdentifier: "latest",
});

if (isError) {
  return (
    <p>Something went wrong</p>
  )
}

return (
    <p>Current block: {isFetching ? "Loading..." : data?.block_number}<p>
)
----

In the aforementioned code, refetchInterval controls the frequency of data refetching. Behind the scenes, Starknet React harnesses https://github.com/TanStack/query/[react-query] for managing state and queries. In addition to useBlock, Starknet React offers other hooks like useContractRead and useWaitForTransaction, which can be configured to update at regular intervals.

The useStarknet hook provides direct access to the ProviderInterface:

[source,typescript]
----
const { library } = useStarknet();

// library.getClassByHash(...)
// library.getTransaction(...)
----

== Contract Interactions

=== Read Functions

Starknet React presents useContractRead, a specialized hook for invoking read functions on contracts, akin to wagmi. This hook functions independently of the user's connection status, as read operations do not necessitate a signer.

[source,typescript]
----
const { data: balance, isLoading, isError, isSuccess } = useContractRead({
    abi: abi_erc20,
    address: CONTRACT_ADDRESS,
    functionName: "allowance",
    args: [owner, spender],
    // watch: true <- refresh at every block
});
----


For ERC20 operations, Starknet React offers a convenient useBalance hook. This hook exempts you from passing an ABI and returns a suitably formatted balance value.

[source,typescript]
----
  const { data, isLoading } = useBalance({
    address,
    token: CONTRACT_ADDRESS, // <- defaults to the ETH token
    // watch: true <- refresh at every block
  });

  return (
    <p>Balance: {data?.formatted} {data?.symbol}</p>
  )
----

=== Write Functions

The useContractWrite hook, designed for write operations, deviates slightly from wagmi. The unique architecture of Starknet facilitates multicall transactions natively at the account level. This feature enhances the user experience when executing multiple transactions, eliminating the need to approve each transaction individually. Starknet React capitalizes on this functionality through the useContractWrite hook. Below is a demonstration of its usage:

[source,typescript]
----
const calls = useMemo(() => {
    // compile the calldata to send
    const calldata = stark.compileCalldata({
      argName: argValue,
    });

    // return a single object for single transaction, 
    // or an array of objects for multicall**
    return {
      contractAddress: CONTRACT_ADDRESS,
      entrypoint: functionName,
      calldata,
    };        
}, [argValue]);


// Returns a function to trigger the transaction
// and state of tx after being sent
const { write, isLoading, data } = useContractWrite({
    calls,
});

function execute() {
  // trigger the transaction
  write();
}

return (
  <button type="button" onClick={execute}>
    Make a transaction
  </button>
)
----

The code snippet begins by compiling the calldata using the compileCalldata utility provided by Starknet.js. This calldata, along with the contract address and entry point, are passed to the useContractWrite hook. The hook returns a write function that is subsequently used to execute the transaction. The hook also provides the transaction's hash and state.

=== A Single Contract Instance

In certain use cases, working with a single contract instance may be preferable to specifying the contract address and ABI in each hook. Starknet React accommodates this requirement with the useContract hook:

[source,typescript]
----
const { contract } = useContract({
    address: CONTRACT_ADDRESS,
    abi: abi_erc20,
});

// Call functions directly on contract
// contract.transfer(...);
// contract.balanceOf(...);
----

== Tracking Transactions

The useTransaction hook allows for the tracking of transaction states given a transaction hash. This hook maintains a cache of all transactions, thereby minimizing redundant network requests.

[source,typescript]
----
const { data, isLoading, error } = useTransaction({ hash: txHash });

return (
  <pre>
    {JSON.stringify(data?.calldata)}
  </pre>
)
----

The full array of available hooks can be discovered in the Starknet React documentation, accessible here: https://apibara.github.io/starknet-react/.

== Conclusion

The Starknet React library offers a comprehensive suite of React hooks and providers, purpose-built for Starknet and the Starknet.js SDK. By taking advantage of these well-crafted tools, developers can build robust decentralized applications that harness the power of the Starknet network.

Through the diligent work of dedicated developers and contributors, Starknet React continues to evolve. New features and optimizations are regularly added, fostering a dynamic and growing ecosystem of decentralized applications.

It's a fascinating journey, filled with innovative technology, endless opportunities, and a growing community of passionate individuals. As a developer, you're not only building applications, but contributing to the advancement of a global, decentralized network.

Have questions or need help? The Starknet community is always ready to assist. Join the https://discord.gg/starknet[Starknet Discord] or explore the https://github.com/starknet-edu/starknetbook[StarknetBook's GitHub repository] for resources and support.


== Further Reading

* https://starknet.js.org[Starknet.js]
* https://www.apibara.com/starknet-react-docs[Starknet React Docs]
* https://github.com/ethereumbook/ethereumbook[Mastering Ethereum]
* https://github.com/bitcoinbook/bitcoinbook[Mastering Bitcoin]

[NOTE]
====
The Book is a community-driven effort created for the community.

* If you've learned something, or not, please take a moment to provide feedback through https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[this 3-question survey].
* If you discover any errors or have additional suggestions, don't hesitate to open an https://github.com/starknet-edu/starknetbook/issues[issue on our GitHub repository].
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____