[id="registers"]

= Registers

We know that the Algebraic RISC operates on memory cells (there are no general purpose registers).
One Cairo instruction may deal with up to 3 values from the memory: it can perform one arithmetic operation (either addition or multiplication) on two of them, and store the result in the third.
In total, each instruction uses 4 memory accesses since it first uses one for fetching the instruction (https://eprint.iacr.org/2021/1063.pdf[Cairo Whitepaper]).

The Cairo CPU operates on 3 registers (`pc`, `ap`, and `fp`) that are used for specifying which memory cells the instruction operates on.
For each of the 3 values in an instruction, you can choose either an address of the form $ap + off$ or $fp + off$ where $off$ is a constant offset in the range $[−215, 215)$.
Thus, an instruction may involve any 3 memory cells out of $2 · 216 = 131072$.
In many aspects, this is similar to having this many registers (implemented in a much cheaper way).
An offset is an addition or substraction to a cell in the memory, e.g., $[fp - 1] = [ap - 2] + [fp + 4]$ where $-1$, $-2$ and $+4$ are offsets.
Offsets allow us to have relative memory positions.

* The "allocation pointer" (ap) points to the first memory cell that has not been used by the program so far.
Many instructions may increase the value `ap` by one to indicate that another memory cell has been used by the instruction;
similar to what `serialize_word` does when it uses the output builtin memory at  `output_ptr` and then updates its value.
* When a function starts the "frame pointer" register (fp) is initialized to the current value of ap.
During the entire scope of the function (excluding inner function calls) the value of `fp` remains constant.
In particular, when a function, foo, calls an inner function, bar, the value of `fp` changes when bar starts but is restored when bar ends.
The idea is that `ap` may change in an unknown way when an inner function is called, so it cannot reliably be used to access the original function's local variables and arguments anymore after that.
Thus, `fp` serves as an anchor to access these values.
* The "`program counter`" (pc) register points to the address in memory of the current Cairo instruction to be executed.
The `pc` starts at the beginning of the program segment;
segment 0.
The CPU (1) fetches the value of that memory cell, (2) performs the instruction expressed by that value (which may affect memory cells or change the flow of the program by assigning a different value to PC), (3) moves `pc` to the next instruction and (4) repeats this process.
In other words, The program counter (pc) keeps the address of the current instruction.
Usually it advances by 1 or 2 per instruction according to the size of the instruction (when the current instruction occupies two field elements, the program counter advances by 2 for the next instruction).

Compile and the run link:registers/cairo/ap_fp_example.cairo[registers/cairo/ap_fp_example.cairo].
The example will print:

[,Bash]
----
1. ap address: 1:3; fp address: 1:3
2. ap address: 1:4; fp address: 1:3; value at address [AP - 1] is 100.
3. ap address: 1:5; fp address: 1:3; value at address [AP - 1] is 200.
4. ap address: 1:6; fp address: 1:3; value at address [AP - 1] is 2:0 (WITH OUTPUT_PTR).
5. ap address: 1:9; fp address: 1:8; value at address [AP - 1] is 300 (FOO() FUNCTION).
6. ap address: 1:9; fp address: 1:8; value at address [AP + 2] is 500; we can not get the value at [AP + 1] since it is unknown.
7. ap address: 1:10; fp address: 1:3; value at address [AP - 1] is 600.
----

Note:

. `fp` is initialized to the same value that `ap` takes at the start of a function's scope: during scope of `main` it is `1:3`, during scope of `foo` it is `1:8`.
When the scope of `foo` ends and the program returns to the `main`, `fp` is `1:3` again.
. You can skip memory cells.
During instruction 6.
we set the value in `[ap+2]` without defining `[ap+1]`.
. `[ap]` can store felts but also relocatable addresses as in instruction 4.
where we store the value of `output_ptr`.
. `ap` advances one by one except when a function is called and at the beginning.
Our `ap` starts pointing at 1:3, because the first three memory cells of the execution segment (1:0, 1:1, 1:2) indicate the other segments that will be used, in this case segments 2, 3 and 4.
Segment 2 is used for the output builtin, and segments 3 and 4 are empty segments used for the return values of `fp` an pc.

Run link:registers/cairo/ap_fp_example.cairo[registers/cairo/ap_fp_example.cairo] with the flags `--print_info` and `--print_segments`.
Note:

. Thanks to `--print_info` we can see the register values after execution.

[,Bash]
----
Register values after execution:
pc = 4:0
ap = 1:11
fp = 3:0
----

The final values of the registers are also relocatable.
`ap` remains in the execution segment (1), while the return values of `fp` and `pc` are given their own segments for technical reasons.

. Thanks to `--print_segments` we can see the segment relocation table;

[,Bash]
----
Segment relocation table:
0     1
1     29
2     339
3     340
4     340
----

The table shows the actual (not relative) addresses of the memory cells used by each segment after relocation.
Segments 3-4 are empty segments used to return values ​​from `fp` and `pc`.
As you can see, the memory ends up being continuous: for example segment 1 starts at cell 29, when segment 0 ends and continues to cell 338, remember we set the value to `[ap+300]` so that the cells 40-337 were automatically filled by the prover.
Then segment 2 starts at the next address, 339.
