[id="segments"]

= Segments

When accessing memory in Cairo we use segments. The segments are memory areas.
These segments will then be concatenated to create a list of segments: our memory.
As we mentioned before, addresses in Cairo are relative: they are not inly relative to each other but also to the segment to which they belong.
Therefore, an address in Cairo is represented like this: `<segment>:<offset>`.
Where `<segment>` is the segment number (we don't know it when writing the program, it is assigned when running our program);
and `<offset>` is the position of the address relative to the segment.
This way of representing addresses is called "relocatable": in the end, when we run our program, these memory cells will be relocated so that the memory ends up being continuous.

The two segments that any Cairo program require are:

* *Segment 0* - Program segment.
Cairo programs are themselves kept in the program segment.
This segment is of fixed length and contains the numeric representation of the Cairo program.
The register `pc` starts here.
* *Segment 1* - Execution segment.
This is where the registers `ap` and `fp` start, and where data generated during the run of a Cairo program (variables, return addresses for function calls, etc.) is stored.
The length of the execution segment is variable, as it depends, for example, on the program input.

As we saw before, we can use builtins which would have their own memory segment.
Compile https://github.com/starknet-edu/starknetbook/blob/main/chapters/modules/chapter_5/pages/builtins/cairo/hash.cairo[builtins/cairo/hash.cairo] (`cairo-compile builtins/cairo/hash.cairo --output hash_compiled.json`) and run it with the `--print-memory` flag (`cairo-run --program hash_compiled.json --print_output --layout=small --print_memory`).
Notice we have values in the Program (0), Execution (1), Output (2), Pedersen (3), and Range Check (4) segments.