[id="bridges"]

= Bridges

It is easy to bridge tokens between Starknet and other chains or exchanges. This can be particlarly useful for testing pusporses, or for learning how Starknet handles inter blockchain messaging. 

== StarkGate

StarkGate is the official bridge between Starknet and Ethereum. It is a smart contract that allows users to deposit and withdraw ERC20 tokens from Starknet.

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
