[id="devnet"]

= Devnet

Transactions on the testnet take time to complete, so it's best to start developing and testing locally. We will use the https://github.com/Shard-Labs/starknet-devnet[devnet developed by Shard Labs]. We can think of this step as an equivalent of Ganache. That is, it emulates the testnet (alpha goerli) of Starknet.

Install using:

[,Bash]
----
pip install starknet-devnet
----

Restart your terminal and run `starknet-devnet --version` to check that the installation was successful. Check that you have https://github.com/Shard-Labs/starknet-devnet/releases[the most up-to-date version]. If you don't have it, run `pip install --upgrade starknet-devnet`. https://shard-labs.github.io/starknet-devnet/docs/intro[Here is the documentation].

Initialize the devnet in a separate shell (or tab) with

[,Bash]
----
starknet-devnet \
    --accounts 3 \
    --gas-price 250 \
    --seed 0 \
    --port 5000
----

We get:

[,Bash]
----
Account #0
Address: 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a
Public key: 0x7e52885445756b313ea16849145363ccb73fb4ab0440dbac333cf9d13de82b9
Private key: 0xe3e70682c2094cac629f6fbed82c07cd

Account #1
Address: 0x69b49c2cc8b16e80e86bfc5b0614a59aa8c9b601569c7b80dde04d3f3151b79
Public key: 0x175666e92f540a19eb24fa299ce04c23f3b75cb2d2332e3ff2021bf6d615fa5
Private key: 0xf728b4fa42485e3a0a5d2f346baa9455

Account #2
Address: 0x7447084f620ba316a42c72ca5b8eefb3fe9a05ca5fe6430c65a69ecc4349b3b
Public key: 0x58100ffde2b924de16520921f6bfe13a8bdde9d296a338b9469dd7370ade6cb
Private key: 0xeb1167b367a9c3787c65c1e582e2e662

Initial balance of each account: 1000000000000000000000 WEI
Seed to replicate this account sequence: 0
WARNING: Use these accounts and their keys ONLY for local testing. DO NOT use them on the mainnet or live networks because you will LOSE FUNDS.

 * Listening on http://127.0.0.1:5000/ (Press CTRL+C to quit)
----

We can run `+curl http://127.0.0.1:5000/is_alive+` to check if the devnet is active. You will receive `Alive!!!%` if it is active.

We created three accounts, with transaction costs of 250 wei per gas. The seed number will help us get the same accounts every time we activate our devnet and add that seed number. In other words, we can choose any seed number, but if we want to get the same accounts, we should select the same seed. We indicated we want to use port `5000`, however, feel free to add any convenient port. Our accounts are based on the code and standards developed by https://github.com/OpenZeppelin/cairo-contracts[Open Zepellin for Cairo].

Please keep track of the address where our devnet is running. The example above is: `+http://127.0.0.1:5000+`. We will use it later.

The interaction with the devnet and the testnet is very similar. If you want to see all the arguments available in the `starknet-devnet` call, you can call `starknet-devnet --help` or go to the https://shard-labs.github.io/starknet-devnet/docs/intro[documentation].

== Contributing 

🎯 +++<strong>+++STARKer: +++</strong>+++ This book is an open source effort, made possible only by contributions from readers like you. If you are interested in making this resource better for other users - please suggest a change by following the instructions https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[here].
