[id="hardhat"]

= Starknet Hardhat Plugin

Hardhat is a popular JS development environment for Ethereum, and if you are already familiar with it and want to use it on Starknet, then this plugin will come in hand!

== Getting Started

Follow these high-level steps to get started with the Starknet Hardhat Plugin:

* Install Hardhat itself (https://hardhat.org/tutorial/creating-a-new-hardhat-project[check this official guide])
* Include the https://github.com/0xSpaceShard/starknet-hardhat-plugin[Hardhat plugin] inside the Hardhat project you created, per instructions in the https://0xspaceshard.github.io/starknet-hardhat-plugin[documentation].
* Create a new project (in our case, we called it hardhat-tutorial) 
* Navigate to the newly created project
* Be sure to run:

[source, bash]
----
npm i @shardlabs/starknet-hardhat-plugin --save-dev
----

* After successfully installing everything, make sure you have docker running as well, or if you have `cairo-lang` installed locally, you can set up venv in your hardhat config file - like https://0xspaceshard.github.io/starknet-hardhat-plugin/docs/intro#existing-virtual-environment[this]!

* Next, add the following line to the top of your `hardhat.config.ts` (or `hardhat.config.js):

[source, bash]
----
import "@shardlabs/starknet-hardhat-plugin";
----

Or:

[source, bash]
----
require("@shardlabs/starknet-hardhat-plugin");
----

== Using the Plugin

With this setup, you can now run Starknet CLI commands as tasks in Hardhat. For instance, to compile a Cairo contract, execute:

[source, bash]
----
npx hardhat starknet-compile-cairo1 [PATH...] 
----

== Example

[NOTE]
====
TODO: We would love to see a simple example of how to use the plugin. If you have one, please submit a PR!
====

In the meantime, you can check the the OxSpaceShard example repository https://github.com/0xSpaceShard/starknet-hardhat-example[here]. The repository contains examples of the capacities of the plugin. You can check the `/scripts` folder with various scenarios.

== Additional Resources

- Official Hardhat Setup Guide: https://hardhat.org/tutorial/creating-a-new-hardhat-project
- Starknet Hardhat Plugin Repository: https://github.com/0xSpaceShard/starknet-hardhat-plugin
- Starknet Hardhat Plugin Documentation: https://0xspaceshard.github.io/starknet-hardhat-plugin
- Starknet Hardhat Example Repository: https://github.com/0xSpaceShard/starknet-hardhat-example


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
