[id="hardhat"]
= Hardhat

With over 17.4 million software developers worldwide using JavaScript regularly, it is our pleasure to introduce a JS native development framework for Cairo 1.0 contracts: Hardhat. To set up this framework, execute the following commands in your project directory:

[source, bash]
----
npm i @shardlabs/starknet-hardhat-plugin --save-dev
----

Next, add the following line to the top of your hardhat.config.ts (or hardhat.config.js):

[source, bash]
----
import "@shardlabs/starknet-hardhat-plugin";
// OR 
require("@shardlabs/starknet-hardhat-plugin");
----

With this setup, you can now run Starknet CLI commands as tasks in Hardhat. For instance, to compile a Cairo 1.0 contract, execute:

[source, bash]
----
npx hardhat starknet-compile-cairo1 [PATH...] 
----

To learn more, visit the [Hardhat Starknet Plugin](https://0xspaceshard.github.io/starknet-hardhat-plugin/) website.


== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
