[id="hardhat"]

= Hardhat

More than 17.4 million software developers around the world use JavaScript on a regular basis. That said, we are glad to say we can provide a JS native development framework for Cairo 1.0 contracts - using good old Hardhat. To set up this framework, run the following commands in your project directory:

[source, bash]
----
npm i @shardlabs/starknet-hardhat-plugin --save-dev
----

And add the following line to the top of your hardhat.config.ts (or hardhat.config.js):

[source, bash]
----
import "@shardlabs/starknet-hardhat-plugin";
// OR 
require("@shardlabs/starknet-hardhat-plugin");
----

Now you can run the Starknet CLI's commands as tasks in Hardhat. For example, to compile a Cairo 1.0 contract, run:

[source, bash]
----
npx hardhat starknet-compile-cairo1 [PATH...] 
----

To learn more - look up their website at https://0xspaceshard.github.io/starknet-hardhat-plugin/[Hardhat Starknet Plugin].

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
