[id="interactive-tutorials"]

= Interactive Tutorials

Thanks to contributions from the StarkNet community, we've created a series of interactive tutorials that will help you get started with StarkNet development. Some of them are ... 

.StarkNet Tutorials
|===
|Tutorial |Description

|https://github.com/shramee/starklings-cairo1[Starklings]|Learn the basics of Cairo 1.0 through your CLI
|https://github.com/starknet-edu[Starkned-Edu]| A set of comprehensive CLI tutorials developed by the Starkware team
|https://starknet.wtf.academy/[WTF Academy]| Gamified learning experience for StarkNet development (Coming Soon)
|https://triality.org/[Triality]| NFT-based online Cairo developer certificate (Coming Soon)
|===

Finally, you can find miscellaneous tutorials and guides on the https://www.starknet-ecosystem.com/en/academy[community page].

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
