[id="nile"]

= Nile

Nile by OpenZeppelin has always been a go-to for Starknet / Cairo developers used to writing code in Python. However, given the recent migration from Cairo 0 to Cairo 1.0 - the Nile project is currently undergoing a revamp. You can track the progress of the project https://github.com/OpenZeppelin/nile-rs[here]

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
