[id="protostar"]

= Protostar

For many developers - it is imperative that they be able to write and test their contracts all in the same language. To that end, our community is proud to present https://docs.swmansion.com/protostar/[Protostar] - a platform which manages your dependencies, compiles your project, runs tests, and lets you interact with the chain through certain commands.

To install Protostar locally, simply open a terminal on Linux or Mac (no Windows yet) and run - 

[source,bash]
----
curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
----

And then restart the terminal. Do make sure your local version of Protostar is at `0.9.3` for it to be compaible with Cairo 1.0. If it is not, simply run - 

[source,bash]
----
protostar upgrade
----

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
