[id="sdk"]

= Commonly Used SDKs 

An SDK, or a Software Development Kit, is a set of software-building tools for a specific platform. An SDK provides application developers a comprehensive collection of tools that enable software developers to build software applications faster and in a more standardized way.

The following SDKs are currently available on Starknet - 

.StarkNet SDK
|===
|Language|Name

|Python|https://github.com/software-mansion/starknet.py[Starknet PY]
|Rust|https://github.com/xJonathanLEI/starknet-rs[Starknet RS]
|Javascript|https://www.starknetjs.com/[Starknet JS]
|Golang|https://github.com/dontpanicdao/caigo[Caigo]

|===

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
