[id="starknet-react"]

= Starknet React

This is an open source collection of React providers and hooks for StarkNet, developed by the https://github.com/apibara[Apibara] team. 

The first thing you need to do to run Starknet-React is install the appropriate package manager, PNPM - 

[source, bash]
----
npm install -g pnpm
----

Then, you can modify a react boilerplate by simply running - 

[source, bash]
----
pnpm add @starknet-react/core
pnpm add get-starknet starknet
----

Finally, wrap the `App` object in your `index` file as follows - 

[source, javascript]
----
import { StarknetConfig } from '@starknet-react/core'

function App() {
  return (
    <StarknetConfig>
      <YourApp />
    </StarknetConfig>
  )
}
----

You can take a look at an example project https://github.com/apibara/starknet-react/tree/main/website[here].

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
