[id="vue-stark-boil"]

= Vue Stark Boil

No matter your preference between Vue and React - the Starknet ecosystem has a suitable framework for you. For starters, let's look at vue-stark-boil, written by the good folks at https://github.com/dontpanicdao[Don't Panic DAO]. 

Simply clone the project to your device from https://github.com/dontpanicdao/vue-stark-boil[here]. To learn more about how Vue works in general - feel free to look at their website https://vuejs.org/[here]. You can use this boilerplate to do all kinds of things, like connecting to wallet, listening for account changes, calling a contract and so on.

When you do clone the project - remember to install all dependencies. You can do this by running the following command in your terminal:

[source, bash]
----
npm install
----

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarkNetBook*

StarkNetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
