[id="index"]

= Starknet 测试简介

====
征集贡献：您的知识和专长可以极大地丰富本章内容。具体来说，我们正在寻找实际的例子来说明合约在每个阶段的测试过程——单元测试、开发网、测试网和主网部署。如果您有兴趣做出贡献，请在我们的 GitHub 存储库上提交合并请求 (PR)。我们非常感谢您有兴趣为这个开源项目做出贡献，我们期待从您的经验中学习。
====

在本章中，我们将探索可用于测试 Cairo 和 Starknet 合约的各种工具。请注意，这是一个快速发展的领域，我们会定期引入新的工具和方法。截至撰写本文时，我们涵盖的工具占可用工具的很大一部分，但我们鼓励读者随时了解最新进展。

目前，我们能够与 Starknet Alpha 进行交互。合约部署的建议步骤是：

1. 单元测试：首先为您的合同编写单元测试。为此，可以使用 Protostar、Nile 或 starknet.py 等工具。
2. 部署：一旦您的单元测试通过，下一步就是在开发网上部署您的合同。 Shard Lab 的 starknet-devnet，在 [**Github**](https://github.com/0xSpaceShard/starknet-devnet) 上可用，是一个不错的选择。
3. 测试网部署：成功部署开发网后，可以将合约部署到测试网，例如 Goerli、alpha-goerli 或 Goerli 2。这可以使用 Protostar、Nile、Hardhat 等工具来实现。
4. 主网部署：最后，在对测试网进行严格测试后，可以将合约部署到 Alpha Starknet（alpha-mainnet）。 用于测试网部署的工具也可以用于主网部署。

请记住，此进程的目的是在将合约部署到实时环境之前，以可控且具有成本效益的方式彻底测试和调试合约。



== **贡献力量**

> 释放你的热情，让《Starknet 之书》更加完美
> 
> 
> *《Starknet 之书》依然在不断完善中，而你的热情、专业知识和独到见解可以将它塑造成一部真正卓越的作品。不要害怕挑战现状或是颠覆这本书！齐心协力，我们一起创造这份宝贵的资源，造福无数人。*
> 
> *为公共事业贡献力量。如果你发现本书有改进的空间，那就抓住机会吧！查看我们的[指南](https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc) 并加入活力满满的社区。一起无畏共建 Starknet！*
> 

— Starknet 社区
