_Copyright 2019 Starkware Industries Ltd. Licensed under the Apache
License, Version 2.0 (the "License"). You may not use this file except
in compliance with the License. You may obtain a copy of the License at
https://www.starkware.co/open-source-license/ Unless required by
applicable law or agreed to in writing, software distributed under the
License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License._

== Part 2: Constraints

* https://www.youtube.com/watch?v=fg3mFPXEYQY[Video Lecture (youtube)]
* https://starkware.co/wp-content/uploads/2021/12/STARK101-Part2.pdf[Slides
(PDF)]

In this part, we are going to create a set of constraints over the trace
`a`. The constraints will be expressions in the trace's cells that are
polynomials (rather than
https://en.wikipedia.org/wiki/Rational_function[rational functions]) if
and only if the trace represents a valid computation of the FibonacciSq.
We will get there in three steps:

. Start by specifying the constraints we care about (the *FibonacciSq
constraints*).
. Translate the FibonacciSq constraints into *polynomial constraints*.
. Translate those into *rational functions* that represent polynomials
if and only if the original constraints hold.

== Step 1 - FibonacciSq Constraints

For `a` to be a correct trace of a FibonacciSq sequence that proves our
claim:

. The first element has to be 1, namely latexmath:[a[0] = 1].
. The last element has to be 2338775057, namely
latexmath:[a[1022] = 2338775057].
. The FibonacciSq rule must apply, that is - for every
latexmath:[i<1021], latexmath:[a][i+2]=a[i+1]²+a[i]².

== Step 2 - Polynomial Constraints

Recall that `f` is a polynomial over the trace domain, that evaluates
exactly to `a` over latexmath:[$G \setminus \{g^{1023}\}$] where
latexmath:[$G=\{g^i : 0\leq i\leq 1023\}$] is the "small" group
generated by latexmath:[$g$].

We now rewrite the above three constraints in a form of polynomial
constraints over `f`:

. latexmath:[$a[0] = 1$] is translated to the polynomial
latexmath:[$f(x) - 1$], which evalutes to 0 for latexmath:[$x = g^0$]
(note that latexmath:[$g^0$] is latexmath:[$1$]).
. latexmath:[$a[1022] = 2338775057$] is translated to the polynomial
latexmath:[$f(x) - 2338775057$], which evalutes to 0 for
latexmath:[$x = g^{1022}$].
. latexmath:[$a[i+2]=a[i+1]^2+a[i]^2$] for every latexmath:[$i<1021$] is
translated to the polynomial
latexmath:[$f(g^2 \cdot x) - (f(g \cdot x))^2 - (f(x))^2$], which
evaluates to 0 for
latexmath:[$x \in G \backslash \{g^{1021}, g^{1022}, g^{1023}\}$].

== Hands on

First, since this is a separate notebook from Part 1, let's run the
following piece of code to have all the variables here with their
correct values. Note that it may take up to 30 seconds, since it reruns
the polynomial interpolation.

[source,python]
----
from channel import Channel
from field import FieldElement
from merkle import MerkleTree
from polynomial import interpolate_poly, X, prod
from tutorial_sessions import part1

a, g, G, h, H, eval_domain, f, f_eval, f_merkle, channel = part1()
print('Success!')
----

You will obtain each of the three constraints as a quotient of two
polynomials, making sure the remainder is the zero polynomial.

== Step 3 - Rational Functions (That are in Fact Polynomials)

Each of the constraints above is represented by a polynomial
latexmath:[$u(x)$] that supposedly evaluates to latexmath:[$0$] on
certain elements of the group latexmath:[$G$]. That is, for some
latexmath:[$x_0, \ldots, x_k \in G$], we claim that

[latexmath]
++++
\[u(x_0) = \ldots = u(x_k) = 0\]
++++

(note that for the first two constraints, latexmath:[$k=0$] because they
only refer to one point and for the third latexmath:[$k=1021$]).

This is equivalent to saying that latexmath:[$u(x)$] is divisible, as a
polynomial, by all of latexmath:[$\{(x-x_i)\}_{i=0}^k$], or,
equivalently, by

[latexmath]
++++
\[\prod_{i=0}^k (x-x_i)\]
++++

Therefore, each of the three constraints above can be written as a
rational function of the form:

[latexmath]
++++
\[\frac{u(x)}{\prod_{i=0}^k (x-x_i)}\]
++++

for the corresponding latexmath:[$u(x)$] and
latexmath:[$\{x_i\}_{i=0}^k$]. In this step we will construct these
three rational functions and show that they are indeed polynomials.

== The First Constraint:

In the first constraint, latexmath:[$f(x) - 1$] and
latexmath:[$\{x_i\} = \{1\}$].

We will now construct the *polynomial*
latexmath:[$p_0(x)=\frac{f(x) - 1}{x - 1}$], making sure that
latexmath:[$f(x) - 1$] is indeed divisible by latexmath:[$(x-1)$].

Solution:

[source,python]
----
numer0 = f - 1
denom0 = X - 1
----

Convince yourself that latexmath:[$f(x) - 1$] vanishes at
latexmath:[$x=1$] by making sure that evaluating this polynomial at
latexmath:[$1$] yields latexmath:[$0$].

The fact that latexmath:[$f(x) - 1$] has a root at latexmath:[$1$]
implies that it is divisible by latexmath:[$(x - 1)$]. Run the following
cell to convince yourself that the remainder of `numer0` modulo `denom0`
is latexmath:[$0$], and therefore division indeed yields a polynomial:

[source,python]
----
numer0 % denom0
----

Run the following cell to construct `p0`, the polynomial representing
the first constraint, by dividing `numer0` by `denom0`:

[source,python]
----
p0 = numer0 / denom0
----

Run test:

[source,python]
----
assert p0(2718) == 2509888982
print('Success!')
----

== The Second Constraint

Construct the polynomial `p1` representing the second constraint,
latexmath:[$p_1(x)= \frac{f(x) - 2338775057}{x - g^{1022}}$], similarly.

Solution:

[source,python]
----
numer1 = f - 2338775057
denom1 = X - g**1022
p1 = numer1 / denom1
----

Run test:

[source,python]
----
assert p1(5772) == 232961446
print('Success!')
----

== The Third Constraint - Succinctness

The last constraint's rational function is slightly more complicated:

[latexmath]
++++
\[p_2(x) = \frac{f(g^2 \cdot x) - (f(g \cdot x))^2 - (f(x))^2}{\prod\limits_{i=0}^{1020} (x-g^i)}\]
++++

whose denominator can be rewritten, so that the entire expression is
easier to compute:

[latexmath]
++++
\[\frac{f(g^2 \cdot x) - (f(g \cdot x))^2 - (f(x))^2}{\frac{x^{1024} - 1}{(x-g^{1021})(x-g^{1022})(x-g^{1023})}}\]
++++

This follows from the equality

[latexmath]
++++
\[\prod\limits_{i=0}^{1023} (x-g^i) = x^{1024} - 1\]
++++

Convince yourself of this equality using the function `prod` that takes
a list and computes its product.

Solution:

[source,python]
----
lst = [(X - g**i) for i in range(1024)]
prod(lst)
----

For more information, see our blog post titled
https://medium.com/starkware/arithmetization-ii-403c3b3f4355[Arithmetization
II].

Let's pause for a moment, and look at a simple example on how
polynomials are composed. After that we will generate the third
constraint.

== Composing Polynomials (a detour)

Create the two polynomials latexmath:[$q(x) = 2x^2 +1$],
latexmath:[$r(x) = x - 3$]:

[source,python]
----
q = 2*X ** 2 + 1
r = X - 3
----

Composing latexmath:[$q$] on latexmath:[$r$] yields a new polynomial:
latexmath:[$q(r(x)) = 2(x-3)^2 + 1 = 2x^2-12x+19$] Run the following
cell to create a third polynomial `cmp` by composing `q` on `r` and
convince yourself that `cmp` is indeed the composition of `q` and `r`:

[source,python]
----
cmp = q(r)
cmp
----

== Back to Polynomial Constraints

Construct the third constraint `p2` in a similar manner to the
construction of `p0` and `p1`, using polynomial composition. Along the
way, verify that latexmath:[$g^{1020}$] is a root of the *numerator*
while latexmath:[$g^{1021}$] is not.

Solution:

[source,python]
----
numer2 = f(g**2 * X) - f(g * X)**2 - f**2
print("Numerator at g^1020 is", numer2(g**1020))
print("Numerator at g^1021 is", numer2(g**1021))
denom2 = (X**1024 - 1) / ((X - g**1021) * (X - g**1022) * (X - g**1023))

p2 = numer2 / denom2
----

Run test:

[source,python]
----
assert p2.degree() == 1023, f'The degree of the third constraint is {p2.degree()} when it should be 1023.'
assert p2(31415) == 2090051528
print('Success!')
----

Run the following cell to observe the degrees of the constraint
polynomials `p0`, `p1` and `p2`, all less than latexmath:[$1024$]. This
will be important in the next part.

[source,python]
----
print('deg p0 =', p0.degree())
print('deg p1 =', p1.degree())
print('deg p2 =', p2.degree())
----

== Step 4 - Composition Polynomial

Recall that we're translating a problem of checking the validity of
three polynomial constraints to checking that each of the rational
functions latexmath:[$p_0, p_1, p_2$] are polynomials.

Our protocol uses an algorithm called
https://eccc.weizmann.ac.il/report/2017/134/[FRI] to do so, which will
be discussed in the next part. In order for the proof to be succinct
(short), we prefer to work with just one rational function instead of
three. For that, we take a random linear combination of
latexmath:[$p_0, p_1, p_2$] called the *composition polynomial* (CP for
short):

[latexmath]
++++
\[CP(x) = \alpha_0 \cdot p_0(x) + \alpha_1 \cdot p_1(x) + \alpha_2 \cdot  p_2(x)\]
++++

where latexmath:[$\alpha_0, \alpha_1, \alpha_2$] are random field elements obtained
from the verifier, or in our case - from the channel.

Proving that (the rational function) latexmath:[$CP$] is a polynomial
guarantess, with high probability, that each of latexmath:[$p_0$],
latexmath:[$p_1$], latexmath:[$p_2$] are themselves polynomials.

In the next part, you will generate a proof for an equivalent fact. But
first, let's create `CP` using `Channel.receive_random_field_element` to
obtain latexmath:[$\alpha_i$].

Solution:

[source,python]
----
def get_CP(channel):
    alpha0 = channel.receive_random_field_element()
    alpha1 = channel.receive_random_field_element()
    alpha2 = channel.receive_random_field_element()
    return alpha0*p0 + alpha1*p1 + alpha2*p2
----

Run test:

[source,python]
----
test_channel = Channel()
CP_test = get_CP(test_channel)
assert CP_test.degree() == 1023, f'The degree of cp is {CP_test.degree()} when it should be 1023.'
assert CP_test(2439804) == 838767343, f'cp(2439804) = {CP_test(2439804)}, when it should be 838767343'
print('Success!')
----

== Commit on the Composition Polynomial

Lastly, we evaluate latexmath:[$cp$] over the evaluation domain
(`eval_domain`), build a Merkle tree on top of that and send its root
over the channel. This is similar to commiting on the LDE trace, as we
did at the end of part 1.

Solution:

[source,python]
----
def CP_eval(channel):
    CP = get_CP(channel)
    return [CP(d) for d in eval_domain]
----

Construct a Merkle Tree over the evaluation and send its root over the
channel.

Solution:

[source,python]
----
channel = Channel()
CP_merkle = MerkleTree(CP_eval(channel))
channel.send(CP_merkle.root)
----

Test your code:

[source,python]
----
assert CP_merkle.root == 'a8c87ef9764af3fa005a1a2cf3ec8db50e754ccb655be7597ead15ed4a9110f1', 'Merkle tree root is wrong.'
print('Success!')
----
