_Copyright 2019 StarkWare Industries Ltd. Licensed under the Apache
License, Version 2.0 (the "License"). You may not use this file except
in compliance with the License. You may obtain a copy of the License at
https://www.starkware.co/open-source-license/ Unless required by
applicable law or agreed to in writing, software distributed under the
License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for
the specific language governing permissions and limitations under the
License._

== Part 1: Trace and Low-Degree Extension

* https://www.youtube.com/watch?v=Y0uJz9VL3Fo[Video Lecture (youtube)]
* https://starkware.co/wp-content/uploads/2021/12/STARK101-Part1.pdf[Slides
(PDF)]

Today we will develop a STARK prover for the FibonacciSq sequence over a
finite field. The FibonacciSq sequence is defined by the recurrence
relation latexmath:[a_{n+2} = a_{n+1} ^2 + a_n ^2]. By the end of the
day, your code will produce a _STARK_ proof attesting to the following
statement: *I know a field element latexmath:[X\in \mathbb{F}] such that
the 1023rd element of the FibonacciSq sequence starting with
latexmath:[1, X] is latexmath:[2338775057]*.

=== The Basics

==== FieldElement class

We use our `+FieldElement+` class to represent field elements. You can
construct instances of `+FieldElement+` from integers, and then add,
multiply, divide, get inverse, and so on. The underlying field of this
class is latexmath:[\mathbb{F}_{3221225473}]
(latexmath:[3221225473 = 3 \cdot 2^{30} + 1]), so all operations are
done modulo 3221225473. Try it by running the following cell (shift +
enter):

[source,python]
----
from field import FieldElement
FieldElement(3221225472) + FieldElement(10)
----

== FibonacciSq Trace

To start, let's construct a list `+a+` of length 1023, whose first two
elements will be FieldElement objects representing 1 and 3141592,
respectively. The next 1021 elements will be the FibonacciSq sequence
induced by these two elements. `+a+` is called the trace of FibonacciSq,
or, when the context is clear, the trace. We can calculate `+a+` as
follows:

[source,python]
----
a = [FieldElement(1), FieldElement(3141592)]
while len(a) < 1023:
    a.append(a[-2] * a[-2] + a[-1] * a[-1])
----

== Test Your Code

Run the next cell to test that you have filled `+a+` correctly. Note
that this is in fact a verifier, albeit very naive and non-succinct one,
as it goes over the sequence, element by element, making sure it is
correct.

[source,python]
----
assert len(a) == 1023, 'The trace must consist of exactly 1023 elements.'
assert a[0] == FieldElement(1), 'The first element in the trace must be the unit element.'
for i in range(2, 1023):
    assert a[i] == a[i - 1] * a[i - 1] + a[i - 2] * a[i - 2], f'The FibonacciSq recursion rule does not apply for index {i}'
assert a[1022] == FieldElement(2338775057), 'Wrong last element!'
print('Success!')
----

== Thinking of Polynomials

We now want to think of the sequence as the evaluation of some, yet
unknown, polynomial latexmath:[f] of degree 1022 (due to the Unisolvence
Theorem). We will choose the domain to be some subgroup
latexmath:[G \subseteq \mathbb{F}^\times] of size 1024, for reasons that
will become clear later.

(Recall that latexmath:[\mathbb{F}^\times] denotes the multiplicative
group of latexmath:[\mathbb{F}], which we get from
latexmath:[\mathbb{F}] by omitting the zero element with the induced
multiplication from the field. A subgroup of size 1024 exists because
latexmath:[\mathbb{F}^\times] is a cyclic group of size
latexmath:[3\cdot 2^{30}], so it contains a subgroup of size
latexmath:[2^i] for any latexmath:[0 \leq i \leq 30]).

=== Find a Group of Size 1024

If we find an element latexmath:[g \in \mathbb{F}] whose
(multiplicative) order is 1024, then latexmath:[g] will generate such a
group. The class `+FieldElement+` provides a static method
`+generator()+` which returns an element that generates
latexmath:[\mathbb{F}^\times] (whose order is
latexmath:[|\mathbb{F}^\times|]).

. Use it to obtain a generator latexmath:[g] for latexmath:[G].
. Create a list called `+G+` with all the elements of latexmath:[G],
such that latexmath:[G[i] := g^i].

_Hint: When latexmath:[k] divides latexmath:[|\mathbb{F}^\times|],
latexmath:[g^k] generates a group of size
latexmath:[\frac {|\mathbb{F}^\times|}{k}], and the n-th power of some
`+FieldElement+` latexmath:[x] can be computed by calling `+x ** n+`._

Solution:

[source,python]
----
g = FieldElement.generator() ** (3 * 2 ** 20)
G = [g ** i for i in range(1024)]
----

Run the next cell to test your code.

[source,python]
----
# Checks that g and G are correct.
assert g.is_order(1024), 'The generator g is of wrong order.'
b = FieldElement(1)
for i in range(1023):
    assert b == G[i], 'The i-th place in G is not equal to the i-th power of g.'
    b = b * g
    assert b != FieldElement(1), f'g is of order {i + 1}'
    
if b * g == FieldElement(1):
    print('Success!')
else:
    print('g is of order > 1024')
----

== Polynomial class

We provide you with a class called `+Polynomial+`. The simplest way to
construct a `+Polynomial+` is by using the variable `+X+` (note that
it's a capital `+X+`) which represents the formal variable
latexmath:[x]:

[source,python]
----
from polynomial import X
# The polynomial 2x^2 + 1.
p = 2*X**2 + 1
# Evaluate p at 2:
print(p(2))
----

== Interpolating a Polynomial

Our `+polynomial+` module provides a Lagrange interpolation function,
whose arguments are:

* x_values: x-values of G that the polynomial's values for them is
known. [List]
* y_values: the corresponding y-values. [List]

It returns the unique `+Polynomial+` of degree < `+len(x_values)+`
instance that evaluates to `+y_values[i]+` on `+x_values[i]+` for all i.

Run the following cell to get help on the function `+interpolate_poly+`.

[source,python]
----
from polynomial import interpolate_poly
interpolate_poly?
----

Suppose that `+a+` contains the values of some polynomial over `+G+`
(except for `+G[-1]+`, since `+a+` is one element shorter). Use
`+interpolate_poly()+` to get `+f+` and get its value at
`+FieldElement(2)+`.

Solution:

[source,python]
----
f = interpolate_poly(G[:-1], a)
v = f(2)
----

Run test:

[source,python]
----
assert v == FieldElement(1302089273)
print('Success!')
----

== Evaluating on a Larger Domain

The trace, viewed as evaluations of a polynomial latexmath:[f] on
latexmath:[G], can now be extended by evaluating latexmath:[f] over a
larger domain, thereby creating a Reed-Solomon error correction code.

=== Cosets

To that end, we must decide on a larger domain on which latexmath:[f]
will be evaluated. We will work with a domain that is 8 times larger
than latexmath:[G]. A natural choice for such a domain is to take some
group latexmath:[H] of size 8192 (which exists because 8192 divides
latexmath:[|\mathbb{F}^\times|]), and shift it by the generator of
latexmath:[\mathbb{F}^\times], thereby obtaining a
https://en.wikipedia.org/wiki/Coset[coset] of latexmath:[H].

Create a list called `+H+` of the elements of latexmath:[H], and
multiply each of them by the generator of latexmath:[\mathbb{F}^\times]
to obtain a list called `+eval_domain+`. In other words, eval_domain =
latexmath:[\{w\cdot h^i | 0 \leq i <8192 \}] for latexmath:[h] the
generator of latexmath:[H] and latexmath:[w] the generator of
latexmath:[\mathbb{F}^\times].

Hint: You already know how to obtain latexmath:[H] - similarly to the
way we got latexmath:[G] a few minutes ago.

Solution:

[source,python]
----
w = FieldElement.generator()
h = w ** ((2 ** 30 * 3) // 8192)
H = [h ** i for i in range(8192)]
eval_domain = [w * x for x in H]
----

Run test:

[source,python]
----
from hashlib import sha256
assert len(set(eval_domain)) == len(eval_domain)
w = FieldElement.generator()
w_inv = w.inverse()
assert '55fe9505f35b6d77660537f6541d441ec1bd919d03901210384c6aa1da2682ce' == sha256(str(H[1]).encode()).hexdigest(),\
    'H list is incorrect. H[1] should be h (i.e., the generator of H).'
for i in range(8192):
    assert ((w_inv * eval_domain[1]) ** i) * w == eval_domain[i]
print('Success!')
----

== Evaluate on a Coset

Time to use `+interpolate_poly+` and `+Polynomial.poly+` to evaluate
over the coset. Note that it is implemented fairely naively in our
Python module, so interpolation may take up to a minute. Indeed -
interpolating and evaluating the trace polynomial is one of the most
computationally-intensive steps in the STARK protocol, even when using
more efficient methods (e.g. FFT).

Solution:

[source,python]
----
f = interpolate_poly(G[:-1], a)
f_eval = [f(d) for d in eval_domain]
----

Run test:

[source,python]
----
# Test against a precomputed hash.
from hashlib import sha256
from channel import serialize
assert '1d357f674c27194715d1440f6a166e30855550cb8cb8efeb72827f6a1bf9b5bb' == sha256(serialize(f_eval).encode()).hexdigest()
print('Success!')
----

== Commitments

We will use https://en.wikipedia.org/wiki/SHA-2[Sha256]-based
https://en.wikipedia.org/wiki/Merkle_tree[Merkle Trees] as our
commitment scheme. A simple implementation of it is available to you in
the `+MerkleTree+` class. Run the next cell (for the sake of this
tutorial, this also serves as a test for correctness of the entire
computation so far):

[source,python]
----
from merkle import MerkleTree
f_merkle = MerkleTree(f_eval)
assert f_merkle.root == '6c266a104eeaceae93c14ad799ce595ec8c2764359d7ad1b4b7c57a4da52be04'
print('Success!')
----

== Channel

Theoretically, a STARK proof system is a protocol for interaction
between two parties - a prover and a verifier. In practice, we convert
this interactive protocol into a non-interactive proof using the
https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic[Fiat-Shamir
Heuristic]. In this tutorial you will use the `+Channel+` class, which
implements this transformation. This channel replaces the verifier in
the sense that the prover (which you are writing) will send data, and
receive random numbers or random `+FieldElement+` instances.

This simple piece of code instantiates a channel object, sends the root
of your Merkle Tree to it. Later, the channel object can be called to
provide random numbers or random field elements.

[source,python]
----
from channel import Channel
channel = Channel()
channel.send(f_merkle.root)
----

Lastly - you can retrieve the proof-so-far (i.e., everything that was
passed in the channel up until a certain point) by printing the member
`+Channel.proof+`.

[source,python]
----
print(channel.proof)
----
