name: Push workflow

on:
  push:
    branches:
      - dev
      - master

jobs:
  release-version:
    name: Releasing a version
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore') || (github.ref_name == 'master' && !contains(github.event.head_commit.message, 'chore(release)')) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.USER_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install node_modules
        run: yarn

      - name: Authenticate with GitHub
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Run release script
        if: ${{ github.ref_name == 'master' }}
        run: yarn run release

      - name: Push to remote branch
        uses: ad-m/github-push-action@master
        with:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
          force: true
